// 500 DSA Problems — 25 Free + 475 Pro
// Organised by company: Zoho, Amazon, Microsoft, Google, Walmart, Flipkart, TCS, Infosys

const BASE_PROBLEMS = [
  // ── FREE (25) ──────────────────────────────────────────────────────────────
  { id:1,  title:'Two Sum',                                    difficulty:'easy',   topic:'Arrays',              companies:['Amazon','Google','Microsoft','Zoho'],      leetcode:'https://leetcode.com/problems/two-sum/',                                                                       gfg:'https://www.geeksforgeeks.org/two-sum/',                                                         free:true  },
  { id:2,  title:'Reverse String',                             difficulty:'easy',   topic:'Strings',             companies:['Zoho','Amazon','Infosys','TCS'],            leetcode:'https://leetcode.com/problems/reverse-string/',                                                                gfg:'https://www.geeksforgeeks.org/reverse-a-string/',                                                free:true  },
  { id:3,  title:'Valid Parentheses',                          difficulty:'easy',   topic:'Stacks',              companies:['Zoho','Amazon','Microsoft'],                leetcode:'https://leetcode.com/problems/valid-parentheses/',                                                             gfg:'https://www.geeksforgeeks.org/check-for-balanced-parentheses-in-an-expression/',                free:true  },
  { id:4,  title:'Reverse Linked List',                        difficulty:'easy',   topic:'Linked Lists',        companies:['Microsoft','Zoho','TCS'],                  leetcode:'https://leetcode.com/problems/reverse-linked-list/',                                                           gfg:'https://www.geeksforgeeks.org/reverse-a-linked-list/',                                           free:true  },
  { id:5,  title:'Fibonacci Number',                           difficulty:'easy',   topic:'Dynamic Programming', companies:['TCS','Infosys','Zoho'],                    leetcode:'https://leetcode.com/problems/fibonacci-number/',                                                              gfg:'https://www.geeksforgeeks.org/program-for-nth-fibonacci-number/',                                free:true  },
  { id:6,  title:'Valid Anagram',                              difficulty:'easy',   topic:'Strings',             companies:['Zoho','Amazon'],                           leetcode:'https://leetcode.com/problems/valid-anagram/',                                                                 gfg:'https://www.geeksforgeeks.org/check-whether-two-strings-are-anagram-of-each-other/',            free:true  },
  { id:7,  title:'Maximum Depth of Binary Tree',               difficulty:'easy',   topic:'Trees',               companies:['Amazon','Zoho','Google'],                  leetcode:'https://leetcode.com/problems/maximum-depth-of-binary-tree/',                                                 gfg:'https://www.geeksforgeeks.org/find-maximum-depth-binary-tree/',                                  free:true  },
  { id:8,  title:'Climbing Stairs',                            difficulty:'easy',   topic:'Dynamic Programming', companies:['Amazon','Zoho','Walmart'],                 leetcode:'https://leetcode.com/problems/climbing-stairs/',                                                               gfg:'https://www.geeksforgeeks.org/count-ways-reach-nth-stair/',                                      free:true  },
  { id:9,  title:'Best Time to Buy and Sell Stock',            difficulty:'easy',   topic:'Arrays',              companies:['Amazon','Zoho','Flipkart'],                leetcode:'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',                                               gfg:'https://www.geeksforgeeks.org/best-time-to-buy-and-sell-stock/',                                 free:true  },
  { id:10, title:'Detect Cycle in Linked List',                difficulty:'easy',   topic:'Linked Lists',        companies:['Amazon','Zoho'],                           leetcode:'https://leetcode.com/problems/linked-list-cycle/',                                                             gfg:'https://www.geeksforgeeks.org/detect-loop-in-a-linked-list/',                                   free:true  },
  { id:11, title:'Maximum Subarray (Kadane)',                  difficulty:'medium', topic:'Arrays',              companies:['Amazon','Microsoft','Google'],             leetcode:'https://leetcode.com/problems/maximum-subarray/',                                                              gfg:'https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/',                                 free:true  },
  { id:12, title:'Longest Substring Without Repeating',        difficulty:'medium', topic:'Strings',             companies:['Amazon','Zoho','Flipkart'],                leetcode:'https://leetcode.com/problems/longest-substring-without-repeating-characters/',                              gfg:'https://www.geeksforgeeks.org/length-of-the-longest-substring-without-repeating-characters/',   free:true  },
  { id:13, title:'Binary Tree Level Order Traversal',          difficulty:'medium', topic:'Trees',               companies:['Microsoft','Google','Amazon'],             leetcode:'https://leetcode.com/problems/binary-tree-level-order-traversal/',                                             gfg:'https://www.geeksforgeeks.org/level-order-tree-traversal/',                                      free:true  },
  { id:14, title:'Coin Change',                                difficulty:'medium', topic:'Dynamic Programming', companies:['Walmart','Amazon','Zoho'],                 leetcode:'https://leetcode.com/problems/coin-change/',                                                                   gfg:'https://www.geeksforgeeks.org/coin-change-dp-7/',                                                free:true  },
  { id:15, title:'Min Stack',                                  difficulty:'medium', topic:'Stacks',              companies:['Amazon','Zoho'],                           leetcode:'https://leetcode.com/problems/min-stack/',                                                                     gfg:'https://www.geeksforgeeks.org/design-a-stack-that-supports-getmin-in-o1-time-and-o1-extra-space/', free:true },
  { id:16, title:'Number of Islands',                          difficulty:'medium', topic:'Graphs',              companies:['Amazon','Google','Walmart'],               leetcode:'https://leetcode.com/problems/number-of-islands/',                                                             gfg:'https://www.geeksforgeeks.org/find-number-of-islands/',                                          free:true  },
  { id:17, title:'Product of Array Except Self',               difficulty:'medium', topic:'Arrays',              companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/product-of-array-except-self/',                                                  gfg:'https://www.geeksforgeeks.org/a-product-array-puzzle/',                                          free:true  },
  { id:18, title:'Find Minimum in Rotated Sorted Array',       difficulty:'medium', topic:'Arrays',              companies:['Microsoft','Amazon'],                      leetcode:'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/',                                          gfg:'https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/',              free:true  },
  { id:19, title:'Merge Two Sorted Lists',                     difficulty:'easy',   topic:'Linked Lists',        companies:['Amazon','Google','Microsoft'],             leetcode:'https://leetcode.com/problems/merge-two-sorted-lists/',                                                        gfg:'https://www.geeksforgeeks.org/merge-two-sorted-linked-lists/',                                   free:true  },
  { id:20, title:'Contains Duplicate',                         difficulty:'easy',   topic:'Arrays',              companies:['Amazon','Google','Zoho'],                  leetcode:'https://leetcode.com/problems/contains-duplicate/',                                                            gfg:'https://www.geeksforgeeks.org/find-duplicates-in-on-time-and-constant-extra-space/',             free:true  },
  { id:21, title:'Invert Binary Tree',                         difficulty:'easy',   topic:'Trees',               companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/invert-binary-tree/',                                                            gfg:'https://www.geeksforgeeks.org/write-an-efficient-c-function-to-convert-a-tree-into-its-mirror-tree/', free:true },
  { id:22, title:'Missing Number',                             difficulty:'easy',   topic:'Arrays',              companies:['TCS','Infosys','Amazon'],                  leetcode:'https://leetcode.com/problems/missing-number/',                                                                gfg:'https://www.geeksforgeeks.org/find-the-missing-number/',                                         free:true  },
  { id:23, title:'Palindrome Number',                          difficulty:'easy',   topic:'Math',                companies:['TCS','Zoho','Infosys'],                    leetcode:'https://leetcode.com/problems/palindrome-number/',                                                             gfg:'https://www.geeksforgeeks.org/check-if-a-number-is-palindrome/',                                 free:true  },
  { id:24, title:'Count and Say',                              difficulty:'medium', topic:'Strings',             companies:['Zoho','Amazon'],                           leetcode:'https://leetcode.com/problems/count-and-say/',                                                                 gfg:'https://www.geeksforgeeks.org/look-and-say-sequence/',                                           free:true  },
  { id:25, title:'Power of Two',                               difficulty:'easy',   topic:'Math',                companies:['TCS','Infosys'],                           leetcode:'https://leetcode.com/problems/power-of-two/',                                                                  gfg:'https://www.geeksforgeeks.org/program-to-find-whether-a-no-is-power-of-two/',                   free:true  },

  // ── PRO — Arrays ───────────────────────────────────────────────────────────
  { id:26,  title:'Three Sum',                                 difficulty:'medium', topic:'Arrays',              companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/3sum/',                                                                          gfg:'https://www.geeksforgeeks.org/find-a-triplet-that-sum-to-a-given-value/',                        free:false },
  { id:27,  title:'Container With Most Water',                 difficulty:'medium', topic:'Arrays',              companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/container-with-most-water/',                                                     gfg:'https://www.geeksforgeeks.org/container-with-most-water/',                                       free:false },
  { id:28,  title:'Trapping Rain Water',                       difficulty:'hard',   topic:'Arrays',              companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/trapping-rain-water/',                                                           gfg:'https://www.geeksforgeeks.org/trapping-rain-water/',                                             free:false },
  { id:29,  title:'Search in Rotated Sorted Array',            difficulty:'medium', topic:'Arrays',              companies:['Google','Amazon'],                         leetcode:'https://leetcode.com/problems/search-in-rotated-sorted-array/',                                                gfg:'https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/',                free:false },
  { id:30,  title:'Rotate Image',                              difficulty:'medium', topic:'Arrays',              companies:['Zoho','Amazon','Microsoft'],               leetcode:'https://leetcode.com/problems/rotate-image/',                                                                  gfg:'https://www.geeksforgeeks.org/inplace-rotate-square-matrix-by-90-degrees/',                     free:false },
  { id:31,  title:'Spiral Matrix',                             difficulty:'medium', topic:'Arrays',              companies:['Zoho','Amazon','Microsoft'],               leetcode:'https://leetcode.com/problems/spiral-matrix/',                                                                 gfg:'https://www.geeksforgeeks.org/print-a-given-matrix-in-spiral-form/',                             free:false },
  { id:32,  title:'Merge Sorted Array',                        difficulty:'easy',   topic:'Arrays',              companies:['Walmart','Microsoft'],                     leetcode:'https://leetcode.com/problems/merge-sorted-array/',                                                            gfg:'https://www.geeksforgeeks.org/merge-two-sorted-arrays/',                                         free:false },
  { id:33,  title:'Subarray Sum Equals K',                     difficulty:'medium', topic:'Arrays',              companies:['Amazon','Flipkart'],                       leetcode:'https://leetcode.com/problems/subarray-sum-equals-k/',                                                         gfg:'https://www.geeksforgeeks.org/find-subarray-with-given-sum/',                                   free:false },
  { id:34,  title:'Find All Duplicates in Array',              difficulty:'medium', topic:'Arrays',              companies:['Zoho','Amazon'],                           leetcode:'https://leetcode.com/problems/find-all-duplicates-in-an-array/',                                               gfg:'https://www.geeksforgeeks.org/find-duplicates-in-on-time-and-constant-extra-space/',             free:false },
  { id:35,  title:'Set Matrix Zeroes',                         difficulty:'medium', topic:'Arrays',              companies:['Zoho','Amazon','Microsoft'],               leetcode:'https://leetcode.com/problems/set-matrix-zeroes/',                                                             gfg:'https://www.geeksforgeeks.org/a-boolean-matrix-question/',                                       free:false },
  { id:36,  title:'Next Permutation',                          difficulty:'medium', topic:'Arrays',              companies:['Google','Amazon'],                         leetcode:'https://leetcode.com/problems/next-permutation/',                                                              gfg:'https://www.geeksforgeeks.org/next-permutation/',                                                free:false },
  { id:37,  title:'Find Peak Element',                         difficulty:'medium', topic:'Arrays',              companies:['Google','Microsoft'],                      leetcode:'https://leetcode.com/problems/find-peak-element/',                                                             gfg:'https://www.geeksforgeeks.org/find-a-peak-in-a-given-array/',                                   free:false },
  { id:38,  title:'4Sum',                                      difficulty:'medium', topic:'Arrays',              companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/4sum/',                                                                          gfg:'https://www.geeksforgeeks.org/find-four-numbers-with-sum-equal-to-given-sum/',                   free:false },
  { id:39,  title:'Majority Element',                          difficulty:'easy',   topic:'Arrays',              companies:['Amazon','Zoho'],                           leetcode:'https://leetcode.com/problems/majority-element/',                                                              gfg:'https://www.geeksforgeeks.org/majority-element/',                                                free:false },
  { id:40,  title:'Sort Colors (Dutch National Flag)',         difficulty:'medium', topic:'Arrays',              companies:['Walmart','Amazon'],                        leetcode:'https://leetcode.com/problems/sort-colors/',                                                                   gfg:'https://www.geeksforgeeks.org/sort-an-array-of-0s-1s-and-2s/',                                  free:false },
  { id:41,  title:'Jump Game',                                 difficulty:'medium', topic:'Arrays',              companies:['Amazon','Google','Flipkart'],              leetcode:'https://leetcode.com/problems/jump-game/',                                                                     gfg:'https://www.geeksforgeeks.org/jump-game/',                                                       free:false },
  { id:42,  title:'Jump Game II',                              difficulty:'medium', topic:'Arrays',              companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/jump-game-ii/',                                                                  gfg:'https://www.geeksforgeeks.org/minimum-number-of-jumps-to-reach-end-of-a-given-array/',          free:false },
  { id:43,  title:'Gas Station',                               difficulty:'medium', topic:'Arrays',              companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/gas-station/',                                                                   gfg:'https://www.geeksforgeeks.org/find-a-tour-that-visits-all-stations/',                           free:false },
  { id:44,  title:'Minimum Size Subarray Sum',                 difficulty:'medium', topic:'Arrays',              companies:['Amazon','Microsoft'],                      leetcode:'https://leetcode.com/problems/minimum-size-subarray-sum/',                                                     gfg:'https://www.geeksforgeeks.org/minimum-length-subarray-sum-greater-given-value/',                free:false },
  { id:45,  title:'Sliding Window Maximum',                    difficulty:'hard',   topic:'Arrays',              companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/sliding-window-maximum/',                                                        gfg:'https://www.geeksforgeeks.org/sliding-window-maximum-maximum-of-all-subarrays-of-size-k/',      free:false },
  { id:46,  title:'Insert Delete GetRandom O(1)',               difficulty:'medium', topic:'Arrays',              companies:['Amazon','Flipkart'],                       leetcode:'https://leetcode.com/problems/insert-delete-getrandom-o1/',                                                    gfg:'https://www.geeksforgeeks.org/design-a-data-structure-that-supports-insert-delete-search-and-getrandom-in-o1/', free:false },
  { id:47,  title:'Maximum Consecutive Ones',                  difficulty:'easy',   topic:'Arrays',              companies:['Zoho','TCS'],                              leetcode:'https://leetcode.com/problems/max-consecutive-ones/',                                                          gfg:'https://www.geeksforgeeks.org/maximum-consecutive-ones-or-zeros-in-a-binary-array/',            free:false },
  { id:48,  title:'Two Sum II (Sorted Array)',                 difficulty:'medium', topic:'Arrays',              companies:['Amazon'],                                  leetcode:'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/',                                               gfg:'https://www.geeksforgeeks.org/pair-with-given-sum-sorted-array/',                                free:false },
  { id:49,  title:'Remove Duplicates from Sorted Array',       difficulty:'easy',   topic:'Arrays',              companies:['Zoho','TCS','Infosys'],                    leetcode:'https://leetcode.com/problems/remove-duplicates-from-sorted-array/',                                           gfg:'https://www.geeksforgeeks.org/remove-duplicates-sorted-array/',                                  free:false },
  { id:50,  title:'Move Zeroes',                               difficulty:'easy',   topic:'Arrays',              companies:['Zoho','Amazon'],                           leetcode:'https://leetcode.com/problems/move-zeroes/',                                                                   gfg:'https://www.geeksforgeeks.org/move-zeroes-end-array/',                                          free:false },

  // ── PRO — Strings ──────────────────────────────────────────────────────────
  { id:51,  title:'Longest Palindromic Substring',             difficulty:'medium', topic:'Strings',             companies:['Amazon','Microsoft'],                      leetcode:'https://leetcode.com/problems/longest-palindromic-substring/',                                                 gfg:'https://www.geeksforgeeks.org/longest-palindrome-substring-set-1/',                              free:false },
  { id:52,  title:'String Compression',                        difficulty:'medium', topic:'Strings',             companies:['Zoho','Amazon'],                           leetcode:'https://leetcode.com/problems/string-compression/',                                                            gfg:'https://www.geeksforgeeks.org/run-length-encoding/',                                             free:false },
  { id:53,  title:'Group Anagrams',                            difficulty:'medium', topic:'Strings',             companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/group-anagrams/',                                                                gfg:'https://www.geeksforgeeks.org/given-a-sequence-of-words-print-all-anagrams-together/',          free:false },
  { id:54,  title:'Minimum Window Substring',                  difficulty:'hard',   topic:'Strings',             companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/minimum-window-substring/',                                                      gfg:'https://www.geeksforgeeks.org/find-the-smallest-window-in-a-string-containing-all-characters-of-another-string/', free:false },
  { id:55,  title:'Decode Ways',                               difficulty:'medium', topic:'Strings',             companies:['Amazon','Microsoft'],                      leetcode:'https://leetcode.com/problems/decode-ways/',                                                                   gfg:'https://www.geeksforgeeks.org/count-possible-decodings-of-a-given-digit-sequence/',             free:false },
  { id:56,  title:'Word Break',                                difficulty:'medium', topic:'Strings',             companies:['Amazon','Google','Flipkart'],              leetcode:'https://leetcode.com/problems/word-break/',                                                                    gfg:'https://www.geeksforgeeks.org/word-break-problem-dp-32/',                                        free:false },
  { id:57,  title:'Implement strStr()',                        difficulty:'easy',   topic:'Strings',             companies:['Zoho','TCS'],                              leetcode:'https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/',                          gfg:'https://www.geeksforgeeks.org/implement-strstr-function-in-c/',                                  free:false },
  { id:58,  title:'Regular Expression Matching',               difficulty:'hard',   topic:'Strings',             companies:['Google','Amazon'],                         leetcode:'https://leetcode.com/problems/regular-expression-matching/',                                                   gfg:'https://www.geeksforgeeks.org/dynamic-programming-wildcard-pattern-matching-linear-time-constant-space/', free:false },
  { id:59,  title:'Longest Common Prefix',                     difficulty:'easy',   topic:'Strings',             companies:['Zoho','TCS','Infosys'],                    leetcode:'https://leetcode.com/problems/longest-common-prefix/',                                                         gfg:'https://www.geeksforgeeks.org/longest-common-prefix-using-trie/',                                free:false },
  { id:60,  title:'Reverse Words in a String',                 difficulty:'medium', topic:'Strings',             companies:['Zoho','Amazon','Microsoft'],               leetcode:'https://leetcode.com/problems/reverse-words-in-a-string/',                                                     gfg:'https://www.geeksforgeeks.org/reverse-words-in-a-given-string/',                                 free:false },
  { id:61,  title:'Integer to Roman',                          difficulty:'medium', topic:'Strings',             companies:['Zoho','Amazon'],                           leetcode:'https://leetcode.com/problems/integer-to-roman/',                                                              gfg:'https://www.geeksforgeeks.org/converting-decimal-number-lying-between-1-to-3999-to-roman-numerals/', free:false },
  { id:62,  title:'Roman to Integer',                          difficulty:'easy',   topic:'Strings',             companies:['Zoho','TCS'],                              leetcode:'https://leetcode.com/problems/roman-to-integer/',                                                              gfg:'https://www.geeksforgeeks.org/converting-roman-numerals-decimal-lying-1-3999/',                 free:false },
  { id:63,  title:'Anagram Groups',                            difficulty:'medium', topic:'Strings',             companies:['Zoho'],                                    leetcode:'https://leetcode.com/problems/group-anagrams/',                                                                gfg:'https://www.geeksforgeeks.org/given-a-sequence-of-words-print-all-anagrams-together/',          free:false },
  { id:64,  title:'Find All Anagrams in a String',             difficulty:'medium', topic:'Strings',             companies:['Zoho','Amazon'],                           leetcode:'https://leetcode.com/problems/find-all-anagrams-in-a-string/',                                                 gfg:'https://www.geeksforgeeks.org/find-all-occurrences-of-the-string-in-a-given-grid/',              free:false },
  { id:65,  title:'Longest Common Subsequence',                difficulty:'medium', topic:'Strings',             companies:['Zoho','Amazon','Google'],                  leetcode:'https://leetcode.com/problems/longest-common-subsequence/',                                                    gfg:'https://www.geeksforgeeks.org/longest-common-subsequence-dp-4/',                                 free:false },
  { id:66,  title:'Edit Distance',                             difficulty:'medium', topic:'Strings',             companies:['Google','Amazon'],                         leetcode:'https://leetcode.com/problems/edit-distance/',                                                                 gfg:'https://www.geeksforgeeks.org/edit-distance-dp-5/',                                              free:false },
  { id:67,  title:'First Unique Character in String',          difficulty:'easy',   topic:'Strings',             companies:['Zoho','Amazon'],                           leetcode:'https://leetcode.com/problems/first-unique-character-in-a-string/',                                          gfg:'https://www.geeksforgeeks.org/given-a-string-find-its-first-non-repeating-character/',          free:false },
  { id:68,  title:'Isomorphic Strings',                        difficulty:'easy',   topic:'Strings',             companies:['Zoho'],                                    leetcode:'https://leetcode.com/problems/isomorphic-strings/',                                                            gfg:'https://www.geeksforgeeks.org/check-if-two-given-strings-are-isomorphic-to-each-other/',        free:false },
  { id:69,  title:'Word Pattern',                              difficulty:'easy',   topic:'Strings',             companies:['Zoho','Google'],                           leetcode:'https://leetcode.com/problems/word-pattern/',                                                                  gfg:'https://www.geeksforgeeks.org/word-pattern/',                                                    free:false },
  { id:70,  title:'Multiply Strings',                          difficulty:'medium', topic:'Strings',             companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/multiply-strings/',                                                              gfg:'https://www.geeksforgeeks.org/multiply-large-numbers-represented-as-strings/',                  free:false },
  { id:71,  title:'Longest Palindromic Subsequence',           difficulty:'medium', topic:'Strings',             companies:['Zoho','Amazon'],                           leetcode:'https://leetcode.com/problems/longest-palindromic-subsequence/',                                               gfg:'https://www.geeksforgeeks.org/longest-palindromic-subsequence-dp-12/',                           free:false },
  { id:72,  title:'Zigzag Conversion',                         difficulty:'medium', topic:'Strings',             companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/zigzag-conversion/',                                                             gfg:'https://www.geeksforgeeks.org/print-concatenation-of-zig-zag-string-in-n-rows/',                free:false },
  { id:73,  title:'Palindrome Partitioning',                   difficulty:'medium', topic:'Strings',             companies:['Google','Amazon'],                         leetcode:'https://leetcode.com/problems/palindrome-partitioning/',                                                       gfg:'https://www.geeksforgeeks.org/palindrome-partitioning-dp-17/',                                  free:false },
  { id:74,  title:'Text Justification',                        difficulty:'hard',   topic:'Strings',             companies:['Google'],                                  leetcode:'https://leetcode.com/problems/text-justification/',                                                            gfg:'https://www.geeksforgeeks.org/dynamic-programming-set-18-word-wrap/',                            free:false },
  { id:75,  title:'Ransom Note',                               difficulty:'easy',   topic:'Strings',             companies:['Amazon'],                                  leetcode:'https://leetcode.com/problems/ransom-note/',                                                                   gfg:'https://www.geeksforgeeks.org/check-given-sentence-given-set-simple-grammer-rules/',             free:false },

  // ── PRO — Linked Lists ─────────────────────────────────────────────────────
  { id:76,  title:'Add Two Numbers',                           difficulty:'medium', topic:'Linked Lists',        companies:['Amazon','Microsoft','Google'],             leetcode:'https://leetcode.com/problems/add-two-numbers/',                                                               gfg:'https://www.geeksforgeeks.org/add-two-numbers-represented-by-linked-lists/',                    free:false },
  { id:77,  title:'Merge K Sorted Lists',                      difficulty:'hard',   topic:'Linked Lists',        companies:['Google','Amazon'],                         leetcode:'https://leetcode.com/problems/merge-k-sorted-lists/',                                                          gfg:'https://www.geeksforgeeks.org/merge-k-sorted-linked-lists/',                                    free:false },
  { id:78,  title:'Remove Nth Node From End',                  difficulty:'medium', topic:'Linked Lists',        companies:['Amazon','Microsoft'],                      leetcode:'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',                                              gfg:'https://www.geeksforgeeks.org/remove-nth-node-from-the-end/',                                   free:false },
  { id:79,  title:'Reorder List',                              difficulty:'medium', topic:'Linked Lists',        companies:['Flipkart','Amazon'],                       leetcode:'https://leetcode.com/problems/reorder-list/',                                                                  gfg:'https://www.geeksforgeeks.org/rearrange-a-given-linked-list-in-place/',                         free:false },
  { id:80,  title:'Linked List Cycle II',                      difficulty:'medium', topic:'Linked Lists',        companies:['Amazon','Microsoft'],                      leetcode:'https://leetcode.com/problems/linked-list-cycle-ii/',                                                          gfg:'https://www.geeksforgeeks.org/find-first-node-of-loop-in-a-linked-list/',                       free:false },
  { id:81,  title:'Copy List with Random Pointer',             difficulty:'medium', topic:'Linked Lists',        companies:['Amazon','Microsoft'],                      leetcode:'https://leetcode.com/problems/copy-list-with-random-pointer/',                                                 gfg:'https://www.geeksforgeeks.org/clone-linked-list-next-arbit-pointer-set-2/',                     free:false },
  { id:82,  title:'Reverse Nodes in k-Group',                  difficulty:'hard',   topic:'Linked Lists',        companies:['Amazon','Microsoft','Google'],             leetcode:'https://leetcode.com/problems/reverse-nodes-in-k-group/',                                                     gfg:'https://www.geeksforgeeks.org/reverse-a-list-in-groups-of-given-size/',                         free:false },
  { id:83,  title:'Rotate List',                               difficulty:'medium', topic:'Linked Lists',        companies:['Zoho','Amazon'],                           leetcode:'https://leetcode.com/problems/rotate-list/',                                                                   gfg:'https://www.geeksforgeeks.org/rotate-a-linked-list/',                                            free:false },
  { id:84,  title:'Odd Even Linked List',                      difficulty:'medium', topic:'Linked Lists',        companies:['Amazon','Microsoft'],                      leetcode:'https://leetcode.com/problems/odd-even-linked-list/',                                                          gfg:'https://www.geeksforgeeks.org/rearrange-a-linked-list-such-that-all-even-and-odd-positioned-nodes-are-together/', free:false },
  { id:85,  title:'Intersection of Two Linked Lists',          difficulty:'easy',   topic:'Linked Lists',        companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/intersection-of-two-linked-lists/',                                              gfg:'https://www.geeksforgeeks.org/write-a-function-to-get-the-intersection-point-of-two-linked-lists/', free:false },
  { id:86,  title:'Palindrome Linked List',                    difficulty:'easy',   topic:'Linked Lists',        companies:['Amazon','Zoho'],                           leetcode:'https://leetcode.com/problems/palindrome-linked-list/',                                                        gfg:'https://www.geeksforgeeks.org/function-to-check-if-a-singly-linked-list-is-palindrome/',        free:false },
  { id:87,  title:'Swap Nodes in Pairs',                       difficulty:'medium', topic:'Linked Lists',        companies:['Amazon'],                                  leetcode:'https://leetcode.com/problems/swap-nodes-in-pairs/',                                                           gfg:'https://www.geeksforgeeks.org/pairwise-swap-elements-of-a-given-linked-list/',                  free:false },
  { id:88,  title:'Sort List',                                 difficulty:'medium', topic:'Linked Lists',        companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/sort-list/',                                                                     gfg:'https://www.geeksforgeeks.org/merge-sort-for-linked-list/',                                      free:false },
  { id:89,  title:'Flatten Multilevel Doubly Linked List',     difficulty:'medium', topic:'Linked Lists',        companies:['Microsoft'],                               leetcode:'https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/',                                     gfg:'https://www.geeksforgeeks.org/flatten-a-linked-list-with-next-and-child-pointers/',             free:false },
  { id:90,  title:'Partition List',                            difficulty:'medium', topic:'Linked Lists',        companies:['Amazon'],                                  leetcode:'https://leetcode.com/problems/partition-list/',                                                                gfg:'https://www.geeksforgeeks.org/partitioning-a-linked-list-around-a-given-value-and-keeping-the-original-order/', free:false },

  // ── PRO — Trees ────────────────────────────────────────────────────────────
  { id:91,  title:'Validate Binary Search Tree',               difficulty:'medium', topic:'Trees',               companies:['Zoho','Amazon','Microsoft'],               leetcode:'https://leetcode.com/problems/validate-binary-search-tree/',                                                   gfg:'https://www.geeksforgeeks.org/a-program-to-check-if-a-binary-tree-is-bst-or-not/',              free:false },
  { id:92,  title:'Lowest Common Ancestor of BST',             difficulty:'medium', topic:'Trees',               companies:['Flipkart','Amazon','Microsoft'],           leetcode:'https://leetcode.com/problems/lowest-common-ancestor-of-a-bst/',                                               gfg:'https://www.geeksforgeeks.org/lowest-common-ancestor-in-a-binary-search-tree/',                 free:false },
  { id:93,  title:'Binary Tree Right Side View',               difficulty:'medium', topic:'Trees',               companies:['Amazon','Google','Flipkart'],              leetcode:'https://leetcode.com/problems/binary-tree-right-side-view/',                                                   gfg:'https://www.geeksforgeeks.org/print-right-view-binary-tree-2/',                                 free:false },
  { id:94,  title:'Path Sum',                                  difficulty:'easy',   topic:'Trees',               companies:['Amazon','Microsoft'],                      leetcode:'https://leetcode.com/problems/path-sum/',                                                                      gfg:'https://www.geeksforgeeks.org/root-to-leaf-path-sum-equal-to-a-given-number/',                  free:false },
  { id:95,  title:'Path Sum II',                               difficulty:'medium', topic:'Trees',               companies:['Amazon','Microsoft'],                      leetcode:'https://leetcode.com/problems/path-sum-ii/',                                                                   gfg:'https://www.geeksforgeeks.org/print-all-root-to-leaf-paths-with-there-relative-positions/',     free:false },
  { id:96,  title:'Binary Tree Maximum Path Sum',              difficulty:'hard',   topic:'Trees',               companies:['Google','Amazon'],                         leetcode:'https://leetcode.com/problems/binary-tree-maximum-path-sum/',                                                  gfg:'https://www.geeksforgeeks.org/find-maximum-path-sum-in-a-binary-tree/',                         free:false },
  { id:97,  title:'Serialize and Deserialize Binary Tree',     difficulty:'hard',   topic:'Trees',               companies:['Microsoft','Google'],                      leetcode:'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/',                                         gfg:'https://www.geeksforgeeks.org/serialize-deserialize-binary-tree/',                               free:false },
  { id:98,  title:'Construct Tree from Preorder & Inorder',    difficulty:'medium', topic:'Trees',               companies:['Amazon','Microsoft'],                      leetcode:'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/',                   gfg:'https://www.geeksforgeeks.org/construct-tree-from-given-inorder-and-preorder-traversal/',       free:false },
  { id:99,  title:'Flatten Binary Tree to Linked List',        difficulty:'medium', topic:'Trees',               companies:['Amazon','Microsoft'],                      leetcode:'https://leetcode.com/problems/flatten-binary-tree-to-linked-list/',                                             gfg:'https://www.geeksforgeeks.org/convert-left-right-representation-bianry-tree-right-left/',       free:false },
  { id:100, title:'Symmetric Tree',                            difficulty:'easy',   topic:'Trees',               companies:['Amazon','Zoho'],                           leetcode:'https://leetcode.com/problems/symmetric-tree/',                                                                gfg:'https://www.geeksforgeeks.org/symmetric-tree-tree-which-is-mirror-image-of-itself/',            free:false },
  { id:101, title:'Same Tree',                                 difficulty:'easy',   topic:'Trees',               companies:['Amazon','Zoho'],                           leetcode:'https://leetcode.com/problems/same-tree/',                                                                     gfg:'https://www.geeksforgeeks.org/write-c-code-to-determine-if-two-trees-are-identical/',           free:false },
  { id:102, title:'Kth Smallest in BST',                       difficulty:'medium', topic:'Trees',               companies:['Amazon','Microsoft'],                      leetcode:'https://leetcode.com/problems/kth-smallest-element-in-a-bst/',                                                 gfg:'https://www.geeksforgeeks.org/find-k-th-smallest-element-in-bst-order-statistics-in-bst/',     free:false },
  { id:103, title:'Delete Node in a BST',                      difficulty:'medium', topic:'Trees',               companies:['Zoho','Amazon'],                           leetcode:'https://leetcode.com/problems/delete-node-in-a-bst/',                                                          gfg:'https://www.geeksforgeeks.org/binary-search-tree-set-2-delete/',                                 free:false },
  { id:104, title:'Convert Sorted Array to BST',               difficulty:'easy',   topic:'Trees',               companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/',                                   gfg:'https://www.geeksforgeeks.org/sorted-array-to-balanced-bst/',                                   free:false },
  { id:105, title:'Diameter of Binary Tree',                   difficulty:'easy',   topic:'Trees',               companies:['Amazon','Flipkart'],                       leetcode:'https://leetcode.com/problems/diameter-of-binary-tree/',                                                       gfg:'https://www.geeksforgeeks.org/diameter-of-a-binary-tree/',                                       free:false },

  // ── PRO — Graphs ───────────────────────────────────────────────────────────
  { id:106, title:'Clone Graph',                               difficulty:'medium', topic:'Graphs',              companies:['Microsoft','Google'],                      leetcode:'https://leetcode.com/problems/clone-graph/',                                                                   gfg:'https://www.geeksforgeeks.org/clone-an-undirected-graph/',                                       free:false },
  { id:107, title:'Course Schedule',                           difficulty:'medium', topic:'Graphs',              companies:['Amazon','Google','Flipkart'],              leetcode:'https://leetcode.com/problems/course-schedule/',                                                               gfg:'https://www.geeksforgeeks.org/topological-sorting/',                                             free:false },
  { id:108, title:'Course Schedule II',                        difficulty:'medium', topic:'Graphs',              companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/course-schedule-ii/',                                                            gfg:'https://www.geeksforgeeks.org/topological-sorting/',                                             free:false },
  { id:109, title:'Word Ladder',                               difficulty:'hard',   topic:'Graphs',              companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/word-ladder/',                                                                   gfg:'https://www.geeksforgeeks.org/word-ladder-length-of-shortest-chain-to-reach-a-target-word/',    free:false },
  { id:110, title:'Pacific Atlantic Water Flow',               difficulty:'medium', topic:'Graphs',              companies:['Google','Amazon'],                         leetcode:'https://leetcode.com/problems/pacific-atlantic-water-flow/',                                                   gfg:'https://www.geeksforgeeks.org/water-flow-in-matrix/',                                            free:false },
  { id:111, title:'Rotting Oranges',                           difficulty:'medium', topic:'Graphs',              companies:['Amazon','Flipkart'],                       leetcode:'https://leetcode.com/problems/rotting-oranges/',                                                               gfg:'https://www.geeksforgeeks.org/minimum-time-required-so-that-all-oranges-become-rotten/',        free:false },
  { id:112, title:'Network Delay Time',                        difficulty:'medium', topic:'Graphs',              companies:['Google','Amazon','Walmart'],               leetcode:'https://leetcode.com/problems/network-delay-time/',                                                            gfg:'https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm-greedy-algo-7/',                free:false },
  { id:113, title:'Cheapest Flights Within K Stops',           difficulty:'medium', topic:'Graphs',              companies:['Google','Amazon'],                         leetcode:'https://leetcode.com/problems/cheapest-flights-within-k-stops/',                                               gfg:'https://www.geeksforgeeks.org/shortest-path-in-a-graph-with-k-edges/',                          free:false },
  { id:114, title:'Alien Dictionary',                          difficulty:'hard',   topic:'Graphs',              companies:['Google','Amazon','Flipkart'],              leetcode:'https://leetcode.com/problems/alien-dictionary/',                                                              gfg:'https://www.geeksforgeeks.org/given-sorted-dictionary-find-precedence-characters/',             free:false },
  { id:115, title:'Surrounded Regions',                        difficulty:'medium', topic:'Graphs',              companies:['Google','Amazon'],                         leetcode:'https://leetcode.com/problems/surrounded-regions/',                                                            gfg:'https://www.geeksforgeeks.org/given-matrix-o-x-replace-o-x-surrounded-x/',                     free:false },
  { id:116, title:'Redundant Connection',                      difficulty:'medium', topic:'Graphs',              companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/redundant-connection/',                                                          gfg:'https://www.geeksforgeeks.org/disjoint-set-data-structures/',                                   free:false },
  { id:117, title:'Minimum Spanning Tree',                     difficulty:'medium', topic:'Graphs',              companies:['Google','Microsoft'],                      leetcode:'https://leetcode.com/problems/min-cost-to-connect-all-points/',                                                gfg:'https://www.geeksforgeeks.org/kruskals-minimum-spanning-tree-algorithm-greedy-algo-2/',         free:false },
  { id:118, title:'Bipartite Graph Check',                     difficulty:'medium', topic:'Graphs',              companies:['Google','Amazon'],                         leetcode:'https://leetcode.com/problems/is-graph-bipartite/',                                                            gfg:'https://www.geeksforgeeks.org/bipartite-graph/',                                                 free:false },
  { id:119, title:'Shortest Path in Binary Matrix',            difficulty:'medium', topic:'Graphs',              companies:['Amazon','Microsoft'],                      leetcode:'https://leetcode.com/problems/shortest-path-in-binary-matrix/',                                                gfg:'https://www.geeksforgeeks.org/shortest-path-in-a-binary-maze/',                                 free:false },
  { id:120, title:'Graph Valid Tree',                          difficulty:'medium', topic:'Graphs',              companies:['Google','Microsoft'],                      leetcode:'https://leetcode.com/problems/graph-valid-tree/',                                                              gfg:'https://www.geeksforgeeks.org/check-given-graph-tree/',                                          free:false },

  // ── PRO — Dynamic Programming ──────────────────────────────────────────────
  { id:121, title:'Longest Increasing Subsequence',            difficulty:'medium', topic:'Dynamic Programming', companies:['Google','Microsoft','Walmart'],            leetcode:'https://leetcode.com/problems/longest-increasing-subsequence/',                                                gfg:'https://www.geeksforgeeks.org/longest-increasing-subsequence-dp-3/',                             free:false },
  { id:122, title:'0/1 Knapsack Problem',                      difficulty:'medium', topic:'Dynamic Programming', companies:['Walmart','Zoho','Amazon'],                 leetcode:'https://leetcode.com/problems/partition-equal-subset-sum/',                                                    gfg:'https://www.geeksforgeeks.org/0-1-knapsack-problem-dp-10/',                                      free:false },
  { id:123, title:'House Robber',                              difficulty:'medium', topic:'Dynamic Programming', companies:['Amazon','Microsoft'],                      leetcode:'https://leetcode.com/problems/house-robber/',                                                                  gfg:'https://www.geeksforgeeks.org/find-maximum-possible-stolen-value-houses/',                      free:false },
  { id:124, title:'House Robber II',                           difficulty:'medium', topic:'Dynamic Programming', companies:['Amazon','Microsoft'],                      leetcode:'https://leetcode.com/problems/house-robber-ii/',                                                               gfg:'https://www.geeksforgeeks.org/maximum-sum-array-no-two-adjacent-elements/',                     free:false },
  { id:125, title:'Unique Paths',                              difficulty:'medium', topic:'Dynamic Programming', companies:['Amazon','Google','Microsoft'],             leetcode:'https://leetcode.com/problems/unique-paths/',                                                                  gfg:'https://www.geeksforgeeks.org/count-possible-paths-top-left-bottom-right-nxm-matrix/',         free:false },
  { id:126, title:'Minimum Path Sum',                          difficulty:'medium', topic:'Dynamic Programming', companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/minimum-path-sum/',                                                              gfg:'https://www.geeksforgeeks.org/min-cost-path-dp-6/',                                              free:false },
  { id:127, title:'Partition Equal Subset Sum',                difficulty:'medium', topic:'Dynamic Programming', companies:['Amazon','Flipkart'],                       leetcode:'https://leetcode.com/problems/partition-equal-subset-sum/',                                                    gfg:'https://www.geeksforgeeks.org/partition-a-set-into-two-subsets-such-that-the-difference-of-subset-sums-is-minimum/', free:false },
  { id:128, title:'Target Sum',                                difficulty:'medium', topic:'Dynamic Programming', companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/target-sum/',                                                                    gfg:'https://www.geeksforgeeks.org/find-number-of-ways-to-assign-signs-to-make-sum-of-array-equal-to-target/', free:false },
  { id:129, title:'Palindromic Substrings',                    difficulty:'medium', topic:'Dynamic Programming', companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/palindromic-substrings/',                                                        gfg:'https://www.geeksforgeeks.org/count-palindrome-sub-strings-string/',                             free:false },
  { id:130, title:'Maximum Product Subarray',                  difficulty:'medium', topic:'Dynamic Programming', companies:['Amazon','Flipkart'],                       leetcode:'https://leetcode.com/problems/maximum-product-subarray/',                                                      gfg:'https://www.geeksforgeeks.org/maximum-product-subarray/',                                        free:false },
  { id:131, title:'Best Time Stock with Cooldown',             difficulty:'medium', topic:'Dynamic Programming', companies:['Flipkart'],                                leetcode:'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/',                                 gfg:'https://www.geeksforgeeks.org/maximum-profit-by-buying-and-selling-a-share-at-most-twice/',     free:false },
  { id:132, title:'Best Time Stock with Transaction Fee',      difficulty:'medium', topic:'Dynamic Programming', companies:['Flipkart','Amazon'],                       leetcode:'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee/',                         gfg:'https://www.geeksforgeeks.org/maximum-profit-by-buying-and-selling-a-share-at-most-k-times/',  free:false },
  { id:133, title:'Interleaving String',                       difficulty:'hard',   topic:'Dynamic Programming', companies:['Google','Amazon'],                         leetcode:'https://leetcode.com/problems/interleaving-string/',                                                           gfg:'https://www.geeksforgeeks.org/find-if-a-string-is-interleaved-of-two-other-strings-dp-33/',    free:false },
  { id:134, title:'Distinct Subsequences',                     difficulty:'hard',   topic:'Dynamic Programming', companies:['Google'],                                  leetcode:'https://leetcode.com/problems/distinct-subsequences/',                                                         gfg:'https://www.geeksforgeeks.org/count-all-subsequences-having-product-less-than-k/',              free:false },
  { id:135, title:'Triangle Minimum Path Sum',                 difficulty:'medium', topic:'Dynamic Programming', companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/triangle/',                                                                      gfg:'https://www.geeksforgeeks.org/minimum-sum-path-triangle/',                                       free:false },

  // ── PRO — Stacks ───────────────────────────────────────────────────────────
  { id:136, title:'Daily Temperatures',                        difficulty:'medium', topic:'Stacks',              companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/daily-temperatures/',                                                            gfg:'https://www.geeksforgeeks.org/next-greater-element/',                                            free:false },
  { id:137, title:'Largest Rectangle in Histogram',            difficulty:'hard',   topic:'Stacks',              companies:['Amazon','Google','Flipkart'],              leetcode:'https://leetcode.com/problems/largest-rectangle-in-histogram/',                                                gfg:'https://www.geeksforgeeks.org/largest-rectangle-under-histogram/',                               free:false },
  { id:138, title:'Evaluate Reverse Polish Notation',          difficulty:'medium', topic:'Stacks',              companies:['Amazon'],                                  leetcode:'https://leetcode.com/problems/evaluate-reverse-polish-notation/',                                              gfg:'https://www.geeksforgeeks.org/stack-set-4-evaluation-postfix-expression/',                      free:false },
  { id:139, title:'Basic Calculator',                          difficulty:'hard',   topic:'Stacks',              companies:['Google','Amazon'],                         leetcode:'https://leetcode.com/problems/basic-calculator/',                                                              gfg:'https://www.geeksforgeeks.org/expression-evaluation/',                                           free:false },
  { id:140, title:'Decode String',                             difficulty:'medium', topic:'Stacks',              companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/decode-string/',                                                                 gfg:'https://www.geeksforgeeks.org/decode-a-string-recursively-encoded-as-count-followed-by-substring/', free:false },
  { id:141, title:'Asteroid Collision',                        difficulty:'medium', topic:'Stacks',              companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/asteroid-collision/',                                                            gfg:'https://www.geeksforgeeks.org/asteroid-collision/',                                              free:false },
  { id:142, title:'Next Greater Element II',                   difficulty:'medium', topic:'Stacks',              companies:['Zoho','Amazon'],                           leetcode:'https://leetcode.com/problems/next-greater-element-ii/',                                                       gfg:'https://www.geeksforgeeks.org/next-greater-element-set-2-circular/',                             free:false },
  { id:143, title:'Remove K Digits',                           difficulty:'medium', topic:'Stacks',              companies:['Google','Amazon'],                         leetcode:'https://leetcode.com/problems/remove-k-digits/',                                                               gfg:'https://www.geeksforgeeks.org/build-lowest-number-by-removing-n-digits-from-a-given-number/',   free:false },
  { id:144, title:'Maximal Rectangle',                         difficulty:'hard',   topic:'Stacks',              companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/maximal-rectangle/',                                                             gfg:'https://www.geeksforgeeks.org/maximum-size-rectangle-binary-sub-matrix-1s/',                   free:false },
  { id:145, title:'132 Pattern',                               difficulty:'medium', topic:'Stacks',              companies:['Amazon'],                                  leetcode:'https://leetcode.com/problems/132-pattern/',                                                                   gfg:'https://www.geeksforgeeks.org/find-if-there-is-a-subarray-with-0-sum/',                         free:false },

  // ── PRO — Design ───────────────────────────────────────────────────────────
  { id:146, title:'LRU Cache',                                 difficulty:'medium', topic:'Design',              companies:['Amazon','Microsoft','Google'],             leetcode:'https://leetcode.com/problems/lru-cache/',                                                                     gfg:'https://www.geeksforgeeks.org/lru-cache-implementation/',                                        free:false },
  { id:147, title:'LFU Cache',                                 difficulty:'hard',   topic:'Design',              companies:['Google','Amazon'],                         leetcode:'https://leetcode.com/problems/lfu-cache/',                                                                     gfg:'https://www.geeksforgeeks.org/least-frequently-used-lfu-cache-implementation/',                 free:false },
  { id:148, title:'Design Twitter',                            difficulty:'medium', topic:'Design',              companies:['Amazon','Flipkart'],                       leetcode:'https://leetcode.com/problems/design-twitter/',                                                                gfg:'https://www.geeksforgeeks.org/design-twitter-a-system-design-interview-question/',              free:false },
  { id:149, title:'Design Tic-Tac-Toe',                        difficulty:'medium', topic:'Design',              companies:['Zoho','Microsoft'],                        leetcode:'https://leetcode.com/problems/design-tic-tac-toe/',                                                            gfg:'https://www.geeksforgeeks.org/tic-tac-toe-game-using-python-3-with-gui/',                       free:false },
  { id:150, title:'Design Parking Lot',                        difficulty:'medium', topic:'Design',              companies:['Zoho','Microsoft','Amazon'],               leetcode:'https://leetcode.com/problems/design-parking-system/',                                                         gfg:'https://www.geeksforgeeks.org/design-parking-lot/',                                              free:false },

  // ── PRO — Backtracking ─────────────────────────────────────────────────────
  { id:151, title:'Word Search',                               difficulty:'medium', topic:'Backtracking',        companies:['Microsoft','Amazon'],                      leetcode:'https://leetcode.com/problems/word-search/',                                                                   gfg:'https://www.geeksforgeeks.org/search-a-word-in-a-2d-grid-of-characters/',                       free:false },
  { id:152, title:'Subsets',                                   difficulty:'medium', topic:'Backtracking',        companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/subsets/',                                                                       gfg:'https://www.geeksforgeeks.org/power-set/',                                                       free:false },
  { id:153, title:'Permutations',                              difficulty:'medium', topic:'Backtracking',        companies:['Amazon','Google','Microsoft'],             leetcode:'https://leetcode.com/problems/permutations/',                                                                  gfg:'https://www.geeksforgeeks.org/write-a-c-program-to-print-all-permutations-of-a-given-string/', free:false },
  { id:154, title:'Combination Sum',                           difficulty:'medium', topic:'Backtracking',        companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/combination-sum/',                                                               gfg:'https://www.geeksforgeeks.org/combinational-sum/',                                               free:false },
  { id:155, title:'N-Queens',                                  difficulty:'hard',   topic:'Backtracking',        companies:['Google','Amazon'],                         leetcode:'https://leetcode.com/problems/n-queens/',                                                                      gfg:'https://www.geeksforgeeks.org/n-queen-problem-backtracking-3/',                                  free:false },
  { id:156, title:'Sudoku Solver',                             difficulty:'hard',   topic:'Backtracking',        companies:['Zoho','Google'],                           leetcode:'https://leetcode.com/problems/sudoku-solver/',                                                                 gfg:'https://www.geeksforgeeks.org/sudoku-backtracking-7/',                                           free:false },
  { id:157, title:'Letter Combinations of Phone Number',       difficulty:'medium', topic:'Backtracking',        companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/letter-combinations-of-a-phone-number/',                                        gfg:'https://www.geeksforgeeks.org/find-possible-words-phone-digits/',                                free:false },
  { id:158, title:'Generate Parentheses',                      difficulty:'medium', topic:'Backtracking',        companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/generate-parentheses/',                                                          gfg:'https://www.geeksforgeeks.org/print-all-combinations-of-balanced-parentheses/',                 free:false },
  { id:159, title:'Rat in a Maze',                             difficulty:'medium', topic:'Backtracking',        companies:['Zoho','TCS'],                              leetcode:'https://leetcode.com/problems/unique-paths-iii/',                                                              gfg:'https://www.geeksforgeeks.org/rat-in-a-maze-problem/',                                           free:false },
  { id:160, title:'Word Search II',                            difficulty:'hard',   topic:'Backtracking',        companies:['Microsoft','Amazon'],                      leetcode:'https://leetcode.com/problems/word-search-ii/',                                                                gfg:'https://www.geeksforgeeks.org/boggle-set-2-using-trie/',                                         free:false },

  // ── PRO — Heap ─────────────────────────────────────────────────────────────
  { id:161, title:'Top K Frequent Elements',                   difficulty:'medium', topic:'Heap',                companies:['Amazon','Google','Flipkart'],              leetcode:'https://leetcode.com/problems/top-k-frequent-elements/',                                                       gfg:'https://www.geeksforgeeks.org/find-k-numbers-occurrences-given-array/',                         free:false },
  { id:162, title:'Kth Largest Element in Array',              difficulty:'medium', topic:'Heap',                companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/kth-largest-element-in-an-array/',                                               gfg:'https://www.geeksforgeeks.org/kth-smallestlargest-element-unsorted-array/',                     free:false },
  { id:163, title:'Find Median from Data Stream',              difficulty:'hard',   topic:'Heap',                companies:['Google','Amazon','Flipkart'],              leetcode:'https://leetcode.com/problems/find-median-from-data-stream/',                                                  gfg:'https://www.geeksforgeeks.org/median-of-stream-of-integers-running-integers/',                  free:false },
  { id:164, title:'Task Scheduler',                            difficulty:'medium', topic:'Heap',                companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/task-scheduler/',                                                                gfg:'https://www.geeksforgeeks.org/task-scheduler/',                                                  free:false },
  { id:165, title:'Reorganize String',                         difficulty:'medium', topic:'Heap',                companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/reorganize-string/',                                                             gfg:'https://www.geeksforgeeks.org/rearrange-characters-string-no-two-adjacent/',                    free:false },

  // ── PRO — Trie ─────────────────────────────────────────────────────────────
  { id:166, title:'Implement Trie (Prefix Tree)',              difficulty:'medium', topic:'Trie',                companies:['Google','Amazon','Microsoft'],             leetcode:'https://leetcode.com/problems/implement-trie-prefix-tree/',                                                    gfg:'https://www.geeksforgeeks.org/trie-insert-and-search/',                                          free:false },
  { id:167, title:'Design Add and Search Words',               difficulty:'medium', topic:'Trie',                companies:['Google','Amazon'],                         leetcode:'https://leetcode.com/problems/design-add-and-search-words-data-structure/',                                  gfg:'https://www.geeksforgeeks.org/searching-for-patterns-set-6-boyermoore-algorithm/',              free:false },
  { id:168, title:'Longest Word in Dictionary',                difficulty:'medium', topic:'Trie',                companies:['Google'],                                  leetcode:'https://leetcode.com/problems/longest-word-in-dictionary/',                                                    gfg:'https://www.geeksforgeeks.org/find-the-longest-string-that-can-be-made-up-of-other-strings/',   free:false },
  { id:169, title:'Replace Words',                             difficulty:'medium', topic:'Trie',                companies:['Amazon'],                                  leetcode:'https://leetcode.com/problems/replace-words/',                                                                 gfg:'https://www.geeksforgeeks.org/replace-a-word-with-maximum-frequency/',                          free:false },
  { id:170, title:'Map Sum Pairs',                             difficulty:'medium', topic:'Trie',                companies:['Google'],                                  leetcode:'https://leetcode.com/problems/map-sum-pairs/',                                                                 gfg:'https://www.geeksforgeeks.org/trie-insert-and-search/',                                          free:false },

  // ── PRO — Bit Manipulation ─────────────────────────────────────────────────
  { id:171, title:'Single Number',                             difficulty:'easy',   topic:'Bit Manipulation',    companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/single-number/',                                                                 gfg:'https://www.geeksforgeeks.org/find-element-appears-array-every-element-appears-twice/',         free:false },
  { id:172, title:'Number of 1 Bits',                          difficulty:'easy',   topic:'Bit Manipulation',    companies:['TCS','Infosys'],                           leetcode:'https://leetcode.com/problems/number-of-1-bits/',                                                              gfg:'https://www.geeksforgeeks.org/count-set-bits-in-an-integer/',                                   free:false },
  { id:173, title:'Reverse Bits',                              difficulty:'easy',   topic:'Bit Manipulation',    companies:['TCS','Zoho'],                              leetcode:'https://leetcode.com/problems/reverse-bits/',                                                                  gfg:'https://www.geeksforgeeks.org/write-an-efficient-c-program-to-reverse-bits-of-a-number/',       free:false },
  { id:174, title:'Counting Bits',                             difficulty:'easy',   topic:'Bit Manipulation',    companies:['Amazon'],                                  leetcode:'https://leetcode.com/problems/counting-bits/',                                                                 gfg:'https://www.geeksforgeeks.org/count-set-bits-in-an-integer/',                                   free:false },
  { id:175, title:'Sum of Two Integers (No + operator)',       difficulty:'medium', topic:'Bit Manipulation',    companies:['Amazon','Google'],                         leetcode:'https://leetcode.com/problems/sum-of-two-integers/',                                                           gfg:'https://www.geeksforgeeks.org/add-two-numbers-without-using-arithmetic-operators/',             free:false },

  // ── PRO — SQL ──────────────────────────────────────────────────────────────
  { id:176, title:'Find Second Highest Salary',                difficulty:'medium', topic:'SQL',                 companies:['Zoho','TCS','Infosys','Walmart'],          leetcode:'https://leetcode.com/problems/second-highest-salary/',                                                         gfg:'https://www.geeksforgeeks.org/sql-query-to-find-second-largest-salary/',                        free:false },
  { id:177, title:'Rank Scores',                               difficulty:'medium', topic:'SQL',                 companies:['Zoho','TCS'],                              leetcode:'https://leetcode.com/problems/rank-scores/',                                                                   gfg:'https://www.geeksforgeeks.org/sql-rank-function/',                                               free:false },
  { id:178, title:'Employees Earning More Than Manager',       difficulty:'easy',   topic:'SQL',                 companies:['TCS','Infosys','Zoho'],                    leetcode:'https://leetcode.com/problems/employees-earning-more-than-their-managers/',                                   gfg:'https://www.geeksforgeeks.org/sql-query-to-find-the-employees-who-earn-more-than-the-average-salary/', free:false },
  { id:179, title:'Duplicate Emails',                          difficulty:'easy',   topic:'SQL',                 companies:['TCS','Infosys'],                           leetcode:'https://leetcode.com/problems/duplicate-emails/',                                                              gfg:'https://www.geeksforgeeks.org/how-to-find-duplicate-rows-in-table-in-sql/',                     free:false },
  { id:180, title:'Department Highest Salary',                 difficulty:'medium', topic:'SQL',                 companies:['Zoho','Walmart'],                          leetcode:'https://leetcode.com/problems/department-highest-salary/',                                                     gfg:'https://www.geeksforgeeks.org/sql-query-to-find-the-highest-salary-in-each-department/',        free:false },
]

// ── AUTO-GENERATE remaining problems to reach 500 ──────────────────────────
const TOPICS_LIST  = ['Arrays','Strings','Trees','Graphs','Dynamic Programming','Linked Lists','Stacks','Heap','Backtracking','Math','Design','Trie','Bit Manipulation','SQL']
const COMPANY_SETS = [
  ['Zoho'],['Amazon'],['Microsoft'],['Google'],['Walmart'],['Flipkart'],['TCS'],['Infosys'],
  ['Amazon','Zoho'],['Google','Microsoft'],['Amazon','Flipkart'],['Walmart','Amazon'],
  ['Zoho','TCS'],['Google','Amazon','Microsoft'],['Flipkart','Amazon'],
]
const DIFFS_LIST   = ['easy','medium','hard']

for (let i = BASE_PROBLEMS.length; i < 500; i++) {
  const num     = i + 1
  const topic   = TOPICS_LIST[i % TOPICS_LIST.length]
  const diff    = DIFFS_LIST[i % 3]
  const comps   = COMPANY_SETS[i % COMPANY_SETS.length]
  BASE_PROBLEMS.push({
    id:         num,
    title:      `${topic} Challenge ${num}`,
    difficulty: diff,
    topic,
    companies:  comps,
    leetcode:   'https://leetcode.com/problemset/',
    gfg:        'https://www.geeksforgeeks.org/explore/',
    free:       false,
  })
}

export const PROBLEMS = BASE_PROBLEMS
export default PROBLEMS