// PROBLEMS_DATA.js — paste this into your SystemDesignPage or import it

export const PROBLEMS = [

  // ── FREE ──────────────────────────────────────────────────────
  {
    id: 33,
    type: 'LLD',
    title: 'Design Cache (LRU)',
    subtitle: 'Implement LRU Cache',
    difficulty: 'Medium',
    companies: ['Amazon', 'Google'],
    tags: ['HashMap', 'LinkedList'],
    duration: '30 mins',
    free: true,
    description: 'Design and implement a Least Recently Used (LRU) cache with O(1) get and put operations.',
    inputOutput: {
      input:  'put(1,1), put(2,2), get(1), put(3,3), get(2)',
      output: 'get(1) → 1 | get(2) → -1 (evicted)',
    },
    coreConcepts: ['HashMap', 'Doubly Linked List', 'O(1) operations'],
    classes: ['LRUCache', 'Node', 'DoublyLinkedList'],
    expectedFunctions: ['get(key)', 'put(key, value)', 'evictLRU()'],
    howToSolve: [
      'Use HashMap for O(1) key lookup',
      'Use Doubly Linked List to track access order',
      'Move accessed node to front of list',
      'Evict tail node when capacity exceeded',
    ],
    constraints: ['O(1) time for get and put', 'Fixed capacity cache', 'Thread-safe operations'],
    keyComponents: ['LRUCache', 'Node', 'DoublyLinkedList'],
    requirements: {
      functional:    ['get(key)', 'put(key, value)', 'Evict LRU on overflow'],
      nonFunctional: ['O(1) operations', 'Thread-safe'],
    },
    resources: [
      { label: 'LRU Cache — LeetCode #146', url: 'https://leetcode.com/problems/lru-cache/' },
    ],
    solveOptions: [
      { label: 'Solve on LeetCode', url: 'https://leetcode.com/problems/lru-cache/', icon: '💻', desc: 'LeetCode #146 — Classic problem' },
      { label: 'Code on Replit',    url: 'https://replit.com/',                         icon: '🔧', desc: 'Write and run your implementation' },
      { label: 'Draw UML',          url: 'https://app.diagrams.net/',                   icon: '🗂️', desc: 'Class diagram' },
    ],
  },

  // ── PRO ───────────────────────────────────────────────────────
  {
    id: 2,
    type: 'HLD',
    title: 'Design Netflix',
    subtitle: 'Video streaming at 200M+ users',
    difficulty: 'Hard',
    companies: ['Netflix', 'Amazon', 'Google'],
    tags: ['CDN', 'Video Encoding', 'Microservices', 'Streaming'],
    duration: '60 mins',
    free: false,
    description: 'Design a video streaming platform that serves 200 million users globally with low latency and adaptive bitrate streaming.',
    inputOutput: {
      input:  'User requests video "Stranger Things S1E1" from Chennai',
      output: 'Stream served from nearest CDN edge node in adaptive quality (4K→720p based on bandwidth)',
    },
    coreConcepts: ['CDN', 'Adaptive Bitrate Streaming', 'Microservices', 'Recommendation Engine'],
    classes: ['VideoService', 'CDNService', 'TranscoderService', 'RecommendationEngine', 'UserService'],
    expectedFunctions: [
      'uploadVideo(file)',
      'streamVideo(videoId, userId)',
      'transcodeVideo(videoId)',
      'getRecommendations(userId)',
    ],
    howToSolve: [
      'Video uploaded to S3 → sent to transcoder → stored in multiple resolutions',
      'CDN (CloudFront/Akamai) serves video from edge node nearest to user',
      'Client uses HLS/DASH protocol to switch quality based on bandwidth',
      'Kafka events feed ML recommendation pipeline',
      'Cassandra stores content metadata, DynamoDB stores watch history',
    ],
    constraints: ['200M concurrent users', 'Sub-200ms start time', '99.99% uptime', 'Global low latency'],
    keyComponents: ['CDN', 'Video Encoder', 'Recommendation Engine', 'Search Service', 'Payment Service'],
    requirements: {
      functional:    ['Upload & stream videos', 'Multiple resolutions', 'Search content', 'Recommendations', 'Offline download'],
      nonFunctional: ['200M users', 'Global low latency', '99.99% uptime', 'Adaptive bitrate'],
    },
    resources: [
      { label: 'Netflix Tech Blog',            url: 'https://netflixtechblog.com/' },
      { label: 'System Design: Netflix (YT)',  url: 'https://www.youtube.com/watch?v=psQzyFfsUGU' },
    ],
    solveOptions: [
      { label: 'Draw on Excalidraw', url: 'https://excalidraw.com/',     icon: '✏️', desc: 'Architecture diagram' },
      { label: 'Use draw.io',        url: 'https://app.diagrams.net/',   icon: '🗂️', desc: 'Component diagram' },
    ],
  },

  {
    id: 3,
    type: 'LLD',
    title: 'Design Parking Lot',
    subtitle: 'OOP + Design Patterns',
    difficulty: 'Medium',
    companies: ['Amazon', 'Microsoft', 'Apple'],
    tags: ['OOP', 'Design Patterns', 'Singleton', 'Strategy'],
    duration: '45 mins',
    free: false,
    description: 'Design a multi-floor parking lot with different vehicle types, automated ticketing, and fee calculation.',
    inputOutput: {
      input:  'vehicle=Car, entry=09:00, exit=11:30',
      output: 'Ticket issued | Spot: F2-S14 | Fee: ₹50 (2.5 hrs × ₹20)',
    },
    coreConcepts: ['Singleton', 'Strategy Pattern', 'Observer Pattern', 'OOP'],
    classes: ['ParkingLot', 'ParkingFloor', 'ParkingSpot', 'Vehicle', 'Ticket', 'Payment'],
    expectedFunctions: [
      'parkVehicle(vehicle)',
      'exitVehicle(ticket)',
      'calculateFee(ticket)',
      'findNearestSpot(vehicleType)',
    ],
    howToSolve: [
      'ParkingLot as Singleton — single instance manages all floors',
      'Abstract Vehicle class → Motorcycle, Car, Bus, ElectricVehicle',
      'ParkingSpot types: Compact, Large, Handicapped, Electric',
      'Strategy Pattern for pricing (hourly, daily, EV discount)',
      'Observer Pattern: DisplayBoard updates when spots change',
    ],
    constraints: ['Thread-safe for concurrent entries', '4 vehicle types', 'Extensible design'],
    keyComponents: ['ParkingLot', 'ParkingFloor', 'ParkingSpot', 'Vehicle', 'Ticket', 'Payment'],
    requirements: {
      functional:    ['Park vehicle', 'Exit vehicle', 'Calculate charges', 'Find nearest spot', 'Display board'],
      nonFunctional: ['Thread-safe', 'Support 4 vehicle types', 'Extensible'],
    },
    resources: [
      { label: 'Design Parking Lot — LeetCode Discuss', url: 'https://leetcode.com/problems/design-parking-system/' },
      { label: 'Grokking OOD — Parking Lot',            url: 'https://github.com/tssovi/grokking-the-object-oriented-design-interview' },
    ],
    solveOptions: [
      { label: 'LeetCode #1603',    url: 'https://leetcode.com/problems/design-parking-system/', icon: '💻', desc: 'Related LeetCode problem' },
      { label: 'Code on Replit',    url: 'https://replit.com/',                                  icon: '🔧', desc: 'Write full OOP implementation' },
      { label: 'Draw UML on draw.io', url: 'https://app.diagrams.net/',                          icon: '🗂️', desc: 'UML class diagram' },
    ],
  },

  {
    id: 4,
    type: 'HLD',
    title: 'Design WhatsApp',
    subtitle: 'Real-time messaging at 2B users',
    difficulty: 'Hard',
    companies: ['Meta', 'Amazon', 'Google'],
    tags: ['WebSockets', 'Message Queue', 'E2E Encryption', 'Push Notifications'],
    duration: '60 mins',
    free: false,
    description: 'Design a real-time chat application serving 2 billion users with end-to-end encryption and reliable message delivery.',
    inputOutput: {
      input:  'User A sends "Hello" to User B (offline)',
      output: 'Message stored → delivered when B comes online → read receipt sent to A',
    },
    coreConcepts: ['WebSockets', 'Message Queue', 'Signal Protocol (E2E)', 'Fan-out'],
    classes: ['ChatService', 'PresenceService', 'NotificationService', 'MediaService', 'GroupService'],
    expectedFunctions: [
      'sendMessage(senderId, receiverId, content)',
      'getOnlineStatus(userId)',
      'deliverPendingMessages(userId)',
      'encryptMessage(content, publicKey)',
    ],
    howToSolve: [
      'WebSocket persistent connections for real-time delivery',
      'Message flow: Client → Chat Server → Kafka → Recipient Server → Client',
      'HBase for messages (time-series), Cassandra for user/group data',
      'Redis pub/sub for presence (online status), heartbeat every 5s',
      'Signal Protocol for E2E encryption — keys stored only on devices',
    ],
    constraints: ['2B users', 'Sub-100ms delivery', 'E2E encryption', 'Offline message storage'],
    keyComponents: ['Chat Service', 'Presence Service', 'Notification Service', 'Media Service', 'Group Service'],
    requirements: {
      functional:    ['1:1 messaging', 'Group chats', 'Media sharing', 'Read receipts', 'Voice/Video calls'],
      nonFunctional: ['2B users', 'Sub-100ms delivery', 'E2E encryption', 'Offline storage'],
    },
    resources: [
      { label: 'WhatsApp Architecture — High Scalability', url: 'https://highscalability.com/blog/2014/2/26/the-whatsapp-architecture-facebook-bought-for-19-billion.html' },
      { label: 'System Design: Chat App (YT)',             url: 'https://www.youtube.com/watch?v=vvhC64hQZMk' },
    ],
    solveOptions: [
      { label: 'Draw on Excalidraw', url: 'https://excalidraw.com/',   icon: '✏️', desc: 'Architecture diagram' },
      { label: 'Use draw.io',        url: 'https://app.diagrams.net/', icon: '🗂️', desc: 'Component diagram' },
    ],
  },

  {
    id: 5,
    type: 'LLD',
    title: 'Design Amazon Locker',
    subtitle: 'Package delivery & pickup system',
    difficulty: 'Medium',
    companies: ['Amazon'],
    tags: ['OOP', 'State Machine', 'Scheduling', 'Notifications'],
    duration: '40 mins',
    free: false,
    description: 'Design the Amazon Locker system where customers receive an OTP to pick up packages from automated lockers.',
    inputOutput: {
      input:  'Package assigned to Locker L3 | Customer enters OTP: 482910',
      output: 'OTP valid → Locker opens → Package retrieved → Locker marked Available',
    },
    coreConcepts: ['State Pattern', 'Singleton', 'OTP Service', 'Scheduler'],
    classes: ['LockerSystem', 'Locker', 'Package', 'Customer', 'OTPService', 'NotificationService'],
    expectedFunctions: [
      'assignLocker(package)',
      'generateOTP(lockerId)',
      'openLocker(lockerId, otp)',
      'handleExpiry(lockerId)',
    ],
    howToSolve: [
      'Locker states: Available → Reserved → Locked → Expired (State Pattern)',
      'Match locker size (Small/Medium/Large) to package dimensions',
      'On package arrival: assign locker → generate 6-digit OTP → SMS customer',
      'Scheduler checks expired packages (3 days) and auto-releases locker',
      'LockerSystem as Singleton with synchronized blocks for thread safety',
    ],
    constraints: ['Thread-safe concurrent access', 'Multiple locker sizes', 'Audit trail'],
    keyComponents: ['LockerSystem', 'Locker', 'Package', 'Customer', 'OTPService', 'NotificationService'],
    requirements: {
      functional:    ['Assign locker', 'Generate OTP', 'Unlock locker', 'Handle expiry', 'Notify customer'],
      nonFunctional: ['Thread-safe', 'Multiple sizes', 'Audit trail'],
    },
    resources: [
      { label: 'Amazon Locker LLD Discussion', url: 'https://leetcode.com/discuss/interview-question/object-oriented-design/716540/' },
    ],
    solveOptions: [
      { label: 'Code on Replit',       url: 'https://replit.com/',          icon: '🔧', desc: 'Write and run Java/Python code' },
      { label: 'Draw on Excalidraw',   url: 'https://excalidraw.com/',      icon: '✏️', desc: 'State machine diagram' },
      { label: 'Draw UML',             url: 'https://app.diagrams.net/',    icon: '🗂️', desc: 'Class diagram' },
    ],
  },

  {
    id: 6,
    type: 'HLD',
    title: 'Design Google Search',
    subtitle: 'Index the entire web',
    difficulty: 'Hard',
    companies: ['Google'],
    tags: ['Web Crawler', 'Inverted Index', 'PageRank', 'Distributed Systems'],
    duration: '75 mins',
    free: false,
    description: 'Design a web search engine that crawls, indexes, and ranks billions of web pages with sub-500ms query response.',
    inputOutput: {
      input:  'Query: "best DSA books for beginners"',
      output: 'Top 10 ranked results in < 500ms | Spell corrected | Related searches shown',
    },
    coreConcepts: ['Web Crawling', 'Inverted Index', 'PageRank', 'MapReduce'],
    classes: ['WebCrawler', 'Indexer', 'RankingEngine', 'QueryProcessor', 'DocumentStore'],
    expectedFunctions: [
      'crawl(url)',
      'buildInvertedIndex(document)',
      'rankResults(queryTerms)',
      'processQuery(searchString)',
    ],
    howToSolve: [
      'Distributed crawlers with URL frontier queue (BFS), politeness delay, robots.txt',
      'BigTable for raw pages, GFS for large files',
      'Inverted Index: word → [doc1:pos, doc2:pos, ...] for fast lookup',
      'PageRank: link graph analysis via iterative MapReduce',
      'Query: Tokenize → inverted index lookup → score → rank → top-k results',
    ],
    constraints: ['Crawl 10B pages', 'Index freshness', 'Sub-500ms search', 'Spell correction'],
    keyComponents: ['Web Crawler', 'Document Store', 'Inverted Index', 'Ranking Engine', 'Query Processor'],
    requirements: {
      functional:    ['Crawl web pages', 'Index content', 'Search queries', 'Rank results', 'Handle updates'],
      nonFunctional: ['10B pages', 'Index freshness', 'Sub-500ms search', 'Spell correction'],
    },
    resources: [
      { label: 'Google BigTable Paper',         url: 'https://static.googleusercontent.com/media/research.google.com/en//archive/bigtable-osdi06.pdf' },
      { label: 'System Design: Search Engine',  url: 'https://www.youtube.com/watch?v=CeGtqouT8eA' },
    ],
    solveOptions: [
      { label: 'Draw on Excalidraw', url: 'https://excalidraw.com/',   icon: '✏️', desc: 'System architecture' },
      { label: 'Use draw.io',        url: 'https://app.diagrams.net/', icon: '🗂️', desc: 'Component diagram' },
    ],
  },

  {
    id: 7,
    type: 'LLD',
    title: 'Design Chess Game',
    subtitle: 'Complete OOP chess implementation',
    difficulty: 'Hard',
    companies: ['Microsoft', 'Apple', 'Amazon'],
    tags: ['OOP', 'Strategy Pattern', 'Command Pattern', 'State Machine'],
    duration: '50 mins',
    free: false,
    description: 'Design a chess game with all pieces, valid move generation, check/checkmate detection, and game history.',
    inputOutput: {
      input:  'White moves Knight from e1 to f3',
      output: 'Valid move → Board updated → Check if Black King in check → Switch turn',
    },
    coreConcepts: ['Strategy Pattern', 'Command Pattern', 'Observer Pattern', 'OOP Inheritance'],
    classes: ['Board', 'Piece', 'King', 'Queen', 'Rook', 'Bishop', 'Knight', 'Pawn', 'Player', 'Game', 'MoveValidator'],
    expectedFunctions: [
      'getValidMoves(piece, board)',
      'makeMove(from, to)',
      'isInCheck(king, board)',
      'isCheckmate(player, board)',
      'undoMove()',
    ],
    howToSolve: [
      'Abstract Piece class → King, Queen, Rook, Bishop, Knight, Pawn',
      'Each piece implements getValidMoves(board) based on its rules',
      'After every move, verify if opponent King is under attack',
      'Command Pattern: each move is a command object (enables undo/redo)',
      'Observer Pattern: GameEventListener for UI updates (check, checkmate, draw)',
    ],
    constraints: ['All piece movements', 'Castling & en passant', 'Move history', 'Extensible for variants'],
    keyComponents: ['Board', 'Piece (abstract)', 'Player', 'Game', 'MoveValidator', 'GameHistory'],
    requirements: {
      functional:    ['All piece movements', 'Check/Checkmate detection', 'Castling/En passant', 'Move history'],
      nonFunctional: ['Extensible for new game modes', 'Clean separation of concerns'],
    },
    resources: [
      { label: 'Chess LLD — Grokking OOD', url: 'https://github.com/tssovi/grokking-the-object-oriented-design-interview/blob/master/object-oriented-design-case-studies/design-chess.md' },
    ],
    solveOptions: [
      { label: 'Code on LeetCode', url: 'https://leetcode.com/',          icon: '💻', desc: 'Write OOP implementation' },
      { label: 'Code on Replit',   url: 'https://replit.com/',            icon: '🔧', desc: 'Run and test your code' },
      { label: 'Draw UML',         url: 'https://app.diagrams.net/',      icon: '🗂️', desc: 'Class diagram' },
    ],
  },

  {
    id: 8,
    type: 'HLD',
    title: 'Design Uber / Ride Sharing',
    subtitle: 'Real-time matching at global scale',
    difficulty: 'Hard',
    companies: ['Uber', 'Amazon', 'Google'],
    tags: ['Geospatial', 'Real-time Matching', 'WebSockets', 'Surge Pricing'],
    duration: '60 mins',
    free: false,
    description: 'Design a ride-sharing platform that matches riders with drivers in real-time using geospatial indexing.',
    inputOutput: {
      input:  'Rider requests cab at (12.97, 80.24) in Chennai',
      output: 'Nearest driver matched in < 30s | ETA: 4 mins | Fare: ₹120 (surge 1.2x)',
    },
    coreConcepts: ['Geospatial Index', 'Redis GeoSearch', 'WebSockets', 'State Machine'],
    classes: ['LocationService', 'MatchingEngine', 'TripService', 'PaymentService', 'NotificationService'],
    expectedFunctions: [
      'updateDriverLocation(driverId, lat, lng)',
      'requestRide(riderId, lat, lng)',
      'matchDriver(riderId)',
      'calculateSurgePricing(zone)',
    ],
    howToSolve: [
      'Drivers send GPS updates every 5s, stored in Redis with GEOSEARCH',
      'Find drivers within radius → rank by distance + rating → offer to nearest',
      'WebSockets for real-time driver location updates on map',
      'Trip state machine: REQUESTED → ACCEPTED → ARRIVED → IN_PROGRESS → COMPLETED',
      'Surge pricing via demand/supply ratio per geohash zone',
    ],
    constraints: ['< 1 min match time', '1M concurrent users', 'Geospatial queries', 'Surge pricing'],
    keyComponents: ['Location Service', 'Matching Engine', 'Trip Service', 'Payment Service', 'Notification Service'],
    requirements: {
      functional:    ['Request ride', 'Match driver', 'Real-time tracking', 'Fare calculation', 'Ratings'],
      nonFunctional: ['< 1min match', '1M concurrent users', 'Geospatial', 'Surge pricing'],
    },
    resources: [
      { label: 'Uber Engineering Blog',    url: 'https://eng.uber.com/' },
      { label: 'System Design: Uber (YT)', url: 'https://www.youtube.com/watch?v=umWABit-wbk' },
    ],
    solveOptions: [
      { label: 'Draw on Excalidraw', url: 'https://excalidraw.com/',   icon: '✏️', desc: 'System architecture' },
      { label: 'Use draw.io',        url: 'https://app.diagrams.net/', icon: '🗂️', desc: 'Component diagrams' },
    ],
  },

  {
    id: 9,
    type: 'LLD',
    title: 'Design BookMyShow',
    subtitle: 'Movie ticket booking system',
    difficulty: 'Medium',
    companies: ['Amazon', 'Microsoft', 'Google'],
    tags: ['OOP', 'Concurrency', 'Booking', 'Seat Lock'],
    duration: '45 mins',
    free: false,
    description: 'Design a movie ticket booking system with concurrent seat selection, locking, and payment.',
    inputOutput: {
      input:  'User selects seats A3, A4 for show "Interstellar" at PVR Chennai 6PM',
      output: 'Seats locked for 5 min → Payment confirmed → Tickets booked | OR: Seats unavailable',
    },
    coreConcepts: ['Optimistic Locking', 'Redis Distributed Lock', 'State Machine', 'Event-driven'],
    classes: ['Theater', 'Screen', 'Show', 'Seat', 'Booking', 'Payment'],
    expectedFunctions: [
      'searchShows(movie, city, date)',
      'lockSeats(showId, seatIds, userId)',
      'confirmBooking(bookingId, paymentDetails)',
      'cancelBooking(bookingId)',
    ],
    howToSolve: [
      'Seat locking with optimistic locking (version number) + 5-min Redis TTL',
      'Distributed lock (Redisson) to prevent double booking',
      'Classes: Theater → Screen → Show → Seat → Booking → Payment',
      'Seat states: AVAILABLE → LOCKED → BOOKED / Booking: INITIATED → CONFIRMED → CANCELLED',
      'Event-driven: BookingConfirmed → Email/SMS via Kafka consumer',
    ],
    constraints: ['No double booking', 'Concurrent seat selection', 'Multiple cities/screens'],
    keyComponents: ['Theater', 'Show', 'Seat', 'Booking', 'Payment', 'Notification'],
    requirements: {
      functional:    ['Search shows', 'Select seats', 'Book tickets', 'Cancellation', 'Seat lock 5 min'],
      nonFunctional: ['No double booking', 'Concurrent locking', 'Multiple cities'],
    },
    resources: [
      { label: 'BookMyShow LLD — Grokking OOD', url: 'https://github.com/tssovi/grokking-the-object-oriented-design-interview' },
      { label: 'LeetCode Discuss: Ticket Booking', url: 'https://leetcode.com/discuss/interview-question/object-oriented-design/' },
    ],
    solveOptions: [
      { label: 'Code on Replit',     url: 'https://replit.com/',          icon: '🔧', desc: 'Write Java/Python code' },
      { label: 'Draw on Excalidraw', url: 'https://excalidraw.com/',      icon: '✏️', desc: 'Class diagrams' },
      { label: 'Use draw.io',        url: 'https://app.diagrams.net/',    icon: '🗂️', desc: 'Sequence diagram' },
    ],
  },

  {
    id: 10,
    type: 'HLD',
    title: 'Design Twitter / X',
    subtitle: 'Social media at 300M users',
    difficulty: 'Hard',
    companies: ['Twitter', 'Meta', 'Google'],
    tags: ['Fan-out', 'Timeline', 'Trending', 'Redis Sorted Set'],
    duration: '60 mins',
    free: false,
    description: 'Design a social media platform with tweet posting, timeline generation, and real-time trending topics.',
    inputOutput: {
      input:  'User A (10M followers) tweets "Hello World" with #DSA',
      output: 'Fan-out to followers\' timelines | #DSA trending updated | Notifications sent',
    },
    coreConcepts: ['Fan-out on Write/Read', 'Redis Sorted Set', 'Apache Flink', 'Elasticsearch'],
    classes: ['TweetService', 'TimelineService', 'FollowService', 'NotificationService', 'TrendEngine'],
    expectedFunctions: [
      'postTweet(userId, content)',
      'getTimeline(userId, page)',
      'followUser(followerId, followeeId)',
      'getTrending(region)',
    ],
    howToSolve: [
      'Cassandra for tweet storage (time-series), S3+CDN for media',
      'Fan-out on write (push) for regular users, fan-out on read (pull) for celebrities',
      'Redis sorted set per user: timeline:{userId} → [tweetIds by timestamp]',
      'Apache Storm/Flink for real-time hashtag counting with sliding window',
      'Elasticsearch for full-text tweet search',
    ],
    constraints: ['300M users', '500M tweets/day', 'Timeline < 200ms', 'Real-time trends'],
    keyComponents: ['Tweet Service', 'Timeline Service', 'Follow Service', 'Notification Service', 'Trend Engine'],
    requirements: {
      functional:    ['Post tweet', 'Follow/unfollow', 'Timeline feed', 'Search', 'Trending hashtags'],
      nonFunctional: ['300M users', '500M tweets/day', '< 200ms timeline', 'Real-time trends'],
    },
    resources: [
      { label: 'Twitter Engineering Blog',     url: 'https://blog.twitter.com/engineering' },
      { label: 'System Design: Twitter (YT)',  url: 'https://www.youtube.com/watch?v=wYk0xPP_P_8' },
    ],
    solveOptions: [
      { label: 'Draw on Excalidraw', url: 'https://excalidraw.com/',   icon: '✏️', desc: 'Architecture diagram' },
      { label: 'Use draw.io',        url: 'https://app.diagrams.net/', icon: '🗂️', desc: 'Detailed design' },
    ],
  },

  {
    id: 11,
    type: 'HLD',
    title: 'Design Instagram',
    subtitle: 'Photo sharing at 1B users',
    difficulty: 'Hard',
    companies: ['Meta', 'Amazon'],
    tags: ['CDN', 'Image Processing', 'Feed Generation', 'Fan-out'],
    duration: '60 mins',
    free: false,
    description: 'Design a social media platform for sharing photos and videos with feed, stories, likes, and comments.',
    inputOutput: {
      input:  'User uploads photo with caption + 5 hashtags from mobile app',
      output: 'Photo stored in S3 → CDN cached → Feed updated for 2M followers → Push notifications sent',
    },
    coreConcepts: ['CDN', 'Fan-out', 'Redis Cache', 'Kafka Event Streaming'],
    classes: ['FeedService', 'MediaService', 'NotificationService', 'UserService', 'CommentService'],
    expectedFunctions: [
      'uploadPhoto(userId, imageData, caption)',
      'getFeed(userId, page)',
      'likePost(userId, postId)',
      'addComment(userId, postId, text)',
    ],
    howToSolve: [
      'Upload: Client → Upload Server → S3 → thumbnail generation → CDN',
      'Feed: precompute for active users (fan-out on write), pull for inactive',
      'Stories: short-lived media with TTL in Redis/S3',
      'Notifications via Kafka events → FCM/APNS push',
      'User DB (SQL), Media metadata (NoSQL), Feed cache (Redis)',
    ],
    constraints: ['1B users', 'Feed < 200ms', 'High availability media storage', 'Real-time notifications'],
    keyComponents: ['Feed Service', 'Media Service', 'Notification Service', 'User Service', 'Comment Service'],
    requirements: {
      functional:    ['Upload photos/videos', 'Like/Comment', 'Stories', 'Follow/Unfollow', 'Search'],
      nonFunctional: ['1B users', 'Feed < 200ms', 'Highly available storage', 'Real-time notifications'],
    },
    resources: [
      { label: 'Instagram Engineering Blog',   url: 'https://instagram-engineering.com/' },
      { label: 'System Design: Instagram (YT)', url: 'https://www.youtube.com/watch?v=CEe9FJw1q2I' },
    ],
    solveOptions: [
      { label: 'Draw on Excalidraw', url: 'https://excalidraw.com/',   icon: '✏️', desc: 'Architecture diagram' },
      { label: 'Use draw.io',        url: 'https://app.diagrams.net/', icon: '🗂️', desc: 'Component diagram' },
    ],
  },

  {
    id: 12,
    type: 'LLD',
    title: 'Design ATM Machine',
    subtitle: 'Banking OOP design',
    difficulty: 'Medium',
    companies: ['Amazon', 'Microsoft'],
    tags: ['State Machine', 'OOP', 'Encapsulation', 'Security'],
    duration: '40 mins',
    free: false,
    description: 'Design an ATM machine system supporting PIN authentication, cash withdrawal/deposit, and transaction history.',
    inputOutput: {
      input:  'insertCard() → enterPIN(4821) → withdraw(500)',
      output: 'PIN valid → Balance sufficient → Cash dispensed ₹500 → Receipt printed | OR: Invalid PIN / Insufficient Balance',
    },
    coreConcepts: ['State Machine', 'OOP', 'Encapsulation', 'Strategy Pattern'],
    classes: ['ATM', 'BankAccount', 'Card', 'Transaction', 'CashDispenser', 'BankServer'],
    expectedFunctions: [
      'authenticate(pin)',
      'withdraw(amount)',
      'deposit(amount)',
      'checkBalance()',
      'printReceipt(transaction)',
    ],
    howToSolve: [
      'ATM states: Idle → CardInserted → Authenticated → Transaction → Idle',
      'Validate card + PIN against BankServer (external call)',
      'Strategy Pattern for transaction types (withdraw, deposit, transfer)',
      'CashDispenser handles physical cash counting and dispensing',
      'Transaction logs maintained for full audit trail',
    ],
    constraints: ['Secure PIN storage (hashed)', 'Concurrent ATM users', 'Transaction logging'],
    keyComponents: ['ATM', 'BankAccount', 'Card', 'Transaction', 'CashDispenser', 'BankServer'],
    requirements: {
      functional:    ['Validate PIN', 'Withdraw/Deposit', 'Check balance', 'Print receipt', 'Transaction history'],
      nonFunctional: ['Secure PIN', 'Handle concurrent ATMs', 'Extensible for new transaction types'],
    },
    resources: [
      { label: 'ATM LLD — LeetCode Discuss', url: 'https://leetcode.com/discuss/interview-question/object-oriented-design/1820438/ATM-Machine-Low-Level-Design' },
      { label: 'ATM Machine LeetCode #2241', url: 'https://leetcode.com/problems/design-an-atm-machine/' },
    ],
    solveOptions: [
      { label: 'LeetCode #2241', url: 'https://leetcode.com/problems/design-an-atm-machine/', icon: '💻', desc: 'Direct LeetCode problem' },
      { label: 'Code on Replit', url: 'https://replit.com/',                                  icon: '🔧', desc: 'Full OOP implementation' },
      { label: 'Draw UML',       url: 'https://app.diagrams.net/',                            icon: '🗂️', desc: 'State + class diagram' },
    ],
  },

  {
    id: 13,
    type: 'HLD',
    title: 'Design Dropbox',
    subtitle: 'Cloud file storage and sync',
    difficulty: 'Hard',
    companies: ['Amazon', 'Microsoft', 'Apple'],
    tags: ['File Sync', 'Block Storage', 'Conflict Resolution', 'Versioning'],
    duration: '60 mins',
    free: false,
    description: 'Design a cloud file storage system that syncs files across devices, handles versioning, and resolves conflicts.',
    inputOutput: {
      input:  'User edits file.docx on laptop and phone simultaneously',
      output: 'Conflict detected → Both versions saved → User prompted to resolve | OR: Auto-merge if no conflict',
    },
    coreConcepts: ['Block-level Sync', 'Merkle Tree', 'Conflict Resolution', 'Delta Sync'],
    classes: ['FileService', 'SyncService', 'MetadataService', 'ConflictResolver', 'StorageService'],
    expectedFunctions: [
      'uploadFile(userId, file)',
      'syncChanges(deviceId, changes)',
      'detectConflict(fileId, versions)',
      'downloadFile(fileId, version)',
    ],
    howToSolve: [
      'Split files into 4MB blocks, upload only changed blocks (delta sync)',
      'Client detects changes → SyncService → propagate to other devices',
      'Metadata DB stores file info (size, version, last modified, block hashes)',
      'Conflict detection: compare timestamps + checksums from two devices',
      'Version history: maintain last N versions of each file',
    ],
    constraints: ['Low latency sync', 'Millions of files', 'Consistent storage', 'High availability'],
    keyComponents: ['FileService', 'SyncService', 'MetadataService', 'ConflictResolver', 'StorageService'],
    requirements: {
      functional:    ['Upload/Download', 'Sync across devices', 'Conflict handling', 'File sharing', 'Versioning'],
      nonFunctional: ['Low latency sync', 'Millions of files', 'Consistent storage', 'High availability'],
    },
    resources: [
      { label: 'Dropbox Tech Blog',           url: 'https://dropbox.tech/' },
      { label: 'System Design: Dropbox (YT)', url: 'https://www.youtube.com/watch?v=iyhJ3lVYp1Q' },
    ],
    solveOptions: [
      { label: 'Draw on Excalidraw', url: 'https://excalidraw.com/',   icon: '✏️', desc: 'System diagram' },
      { label: 'Use draw.io',        url: 'https://app.diagrams.net/', icon: '🗂️', desc: 'Component diagram' },
    ],
  },

  {
    id: 14,
    type: 'LLD',
    title: 'Design Snake & Ladder',
    subtitle: 'Classic board game OOP',
    difficulty: 'Easy',
    companies: ['Amazon', 'Google'],
    tags: ['OOP', 'Game Design', 'Clean Code'],
    duration: '30 mins',
    free: false,
    description: 'Design the classic Snake & Ladder board game with multiple players, dice rolls, snakes, ladders, and win condition.',
    inputOutput: {
      input:  'Player 1 at pos 15, rolls 3 → lands on 18 (snake head at 18 → tail at 6)',
      output: 'Player 1 moved to position 6 (slid down snake)',
    },
    coreConcepts: ['OOP', 'Random (Dice)', 'HashMap (Snakes/Ladders)', 'Game Loop'],
    classes: ['Board', 'Player', 'Dice', 'Snake', 'Ladder', 'Game'],
    expectedFunctions: [
      'rollDice()',
      'movePlayer(player, steps)',
      'checkSnakeOrLadder(position)',
      'isWinner(player)',
    ],
    howToSolve: [
      'Board stores positions 1-100 with HashMap for snakes (head→tail) and ladders (bottom→top)',
      'Dice generates random 1-6, player moves forward',
      'After each move, check if position has snake head or ladder bottom',
      'Win condition: player reaches exactly position 100',
      'Game loop continues until a player wins',
    ],
    constraints: ['Multiple players', 'Extensible board size', 'Clean separation of concerns'],
    keyComponents: ['Board', 'Player', 'Dice', 'Snake', 'Ladder', 'Game'],
    requirements: {
      functional:    ['Roll dice', 'Move player', 'Climb ladders', 'Slide snakes', 'Detect winner'],
      nonFunctional: ['Extensible board', 'Multiple players', 'Testable logic'],
    },
    resources: [
      { label: 'Snakes and Ladders — LeetCode #909', url: 'https://leetcode.com/problems/snakes-and-ladders/' },
    ],
    solveOptions: [
      { label: 'LeetCode #909',  url: 'https://leetcode.com/problems/snakes-and-ladders/', icon: '💻', desc: 'Direct LeetCode problem' },
      { label: 'Code on Replit', url: 'https://replit.com/',                                icon: '🔧', desc: 'Implement full game logic' },
      { label: 'Draw UML',       url: 'https://app.diagrams.net/',                          icon: '🗂️', desc: 'Class diagram' },
    ],
  },

  {
    id: 15,
    type: 'HLD',
    title: 'Design YouTube',
    subtitle: 'Video platform at 2B users',
    difficulty: 'Hard',
    companies: ['Google', 'Amazon', 'Netflix'],
    tags: ['Video CDN', 'Encoding', 'Recommendations', 'Search'],
    duration: '75 mins',
    free: false,
    description: 'Design a video platform supporting uploads, adaptive streaming, search, and recommendations at massive scale.',
    inputOutput: {
      input:  'Creator uploads 4K video (2GB) | Viewer searches "React tutorial" from India',
      output: 'Video transcoded to 6 resolutions → stored → CDN distributed | Search returns ranked results in < 300ms',
    },
    coreConcepts: ['Adaptive Bitrate (HLS/DASH)', 'CDN', 'ML Recommendations', 'Elasticsearch'],
    classes: ['UploadService', 'StreamingService', 'RecommendationEngine', 'SearchService', 'CDNService'],
    expectedFunctions: [
      'uploadVideo(creatorId, videoFile)',
      'streamVideo(videoId, userId, quality)',
      'searchVideos(query)',
      'getRecommendations(userId)',
    ],
    howToSolve: [
      'Upload: Client → Upload Server → Transcoder → 6 resolutions stored in S3',
      'Streaming: CDN serves via HLS/DASH with adaptive bitrate',
      'Recommendations: event collection → ML pipeline → personalized feed',
      'Search: index video metadata in Elasticsearch for full-text search',
      'Analytics: BigQuery/S3 for views, watch time, engagement metrics',
    ],
    constraints: ['2B users', 'Streaming < 200ms', 'Highly available storage', 'Adaptive bitrate'],
    keyComponents: ['Upload Service', 'Streaming Service', 'Recommendation Engine', 'Search Service', 'CDN'],
    requirements: {
      functional:    ['Upload videos', 'Stream multi-resolution', 'Search', 'Recommend', 'Comments/Likes'],
      nonFunctional: ['2B users', 'Streaming < 200ms', 'High availability', 'Adaptive bitrate'],
    },
    resources: [
      { label: 'System Design: YouTube (YT)', url: 'https://www.youtube.com/watch?v=QE0_3vYtEFA' },
    ],
    solveOptions: [
      { label: 'Draw on Excalidraw', url: 'https://excalidraw.com/',   icon: '✏️', desc: 'Architecture diagram' },
      { label: 'Use draw.io',        url: 'https://app.diagrams.net/', icon: '🗂️', desc: 'Component diagram' },
    ],
  },

  {
    id: 16,
    type: 'LLD',
    title: 'Design Elevator System',
    subtitle: 'Multi-elevator scheduling',
    difficulty: 'Medium',
    companies: ['Amazon', 'Microsoft', 'Apple'],
    tags: ['Scheduling', 'OOP', 'State Machine', 'Observer'],
    duration: '40 mins',
    free: false,
    description: 'Design a building elevator system with multiple elevators, floor requests, and optimal scheduling.',
    inputOutput: {
      input:  'Floor 5 button pressed (UP) | Elevator A at Floor 3 (idle), Elevator B at Floor 7 (moving down)',
      output: 'Elevator A assigned (nearest, same direction) → moves to Floor 5 → doors open',
    },
    coreConcepts: ['State Machine', 'Observer Pattern', 'Scheduling Algorithm', 'Concurrency'],
    classes: ['Elevator', 'ElevatorController', 'FloorRequest', 'Button', 'Scheduler'],
    expectedFunctions: [
      'requestElevator(floor, direction)',
      'assignElevator(request)',
      'moveElevator(elevatorId, targetFloor)',
      'openDoors(elevatorId)',
    ],
    howToSolve: [
      'Elevator states: IDLE → MOVING_UP/DOWN → DOOR_OPEN → IDLE',
      'Scheduler assigns nearest idle elevator (or same-direction moving elevator)',
      'ElevatorController manages all elevators and incoming requests',
      'Observer Pattern: floor panels update when elevator arrives',
      'Concurrent requests handled via request queue per elevator',
    ],
    constraints: ['Minimize wait time', 'Concurrent requests', 'Extensible to more elevators'],
    keyComponents: ['Elevator', 'ElevatorController', 'FloorRequest', 'Button', 'Scheduler'],
    requirements: {
      functional:    ['Call elevator', 'Move elevator', 'Multiple requests', 'Stop at floors', 'Emergency'],
      nonFunctional: ['Minimize wait time', 'Concurrent requests', 'Extensible'],
    },
    resources: [
      { label: 'Design Elevator — LeetCode Discuss', url: 'https://leetcode.com/discuss/interview-question/object-oriented-design/124893/Elevator-Design' },
    ],
    solveOptions: [
      { label: 'Code on Replit', url: 'https://replit.com/',          icon: '🔧', desc: 'Implement classes and logic' },
      { label: 'Draw UML',       url: 'https://app.diagrams.net/',    icon: '🗂️', desc: 'State + class diagram' },
    ],
  },

  {
    id: 17,
    type: 'HLD',
    title: 'Design Zoom / Video Call',
    subtitle: 'Real-time video conferencing',
    difficulty: 'Hard',
    companies: ['Google', 'Amazon', 'Apple'],
    tags: ['WebRTC', 'TURN/STUN', 'SFU', 'Recording'],
    duration: '60 mins',
    free: false,
    description: 'Design a video conferencing platform supporting multi-party calls, screen sharing, recording, and chat.',
    inputOutput: {
      input:  '50-person meeting starts | User behind NAT joins | Screen share enabled',
      output: 'SFU routes streams efficiently | TURN server handles NAT traversal | Recording stored to S3',
    },
    coreConcepts: ['WebRTC', 'SFU (Selective Forwarding Unit)', 'TURN/STUN', 'NAT Traversal'],
    classes: ['SignalingService', 'MediaService', 'ChatService', 'RecordingService', 'PresenceService'],
    expectedFunctions: [
      'createMeeting(hostId)',
      'joinMeeting(meetingId, userId)',
      'startScreenShare(userId)',
      'startRecording(meetingId)',
    ],
    howToSolve: [
      'Signaling server: exchange WebRTC SDP offers/answers between clients',
      'SFU (Selective Forwarding Unit) forwards each stream to all other participants',
      'STUN: clients discover public IP | TURN: relay traffic through server for NAT',
      'Recording: server-side media capture → stored in S3 → transcoded',
      'Presence service tracks who is muted, screen-sharing, or hand-raised',
    ],
    constraints: ['Low latency video/audio', 'Millions of concurrent calls', 'Reliable across NATs'],
    keyComponents: ['Signaling Service', 'Media Service', 'Chat Service', 'Recording Service', 'Presence Service'],
    requirements: {
      functional:    ['1:1 & group video', 'Screen sharing', 'Recording', 'Chat', 'Mute/unmute'],
      nonFunctional: ['Low latency', 'Millions of concurrent calls', 'Reliable connectivity'],
    },
    resources: [
      { label: 'Zoom Engineering Blog',    url: 'https://blog.zoom.us/' },
      { label: 'System Design: Zoom (YT)', url: 'https://www.youtube.com/watch?v=Y5Z5z08ajO0' },
    ],
    solveOptions: [
      { label: 'Draw on Excalidraw', url: 'https://excalidraw.com/',   icon: '✏️', desc: 'Architecture diagram' },
      { label: 'Use draw.io',        url: 'https://app.diagrams.net/', icon: '🗂️', desc: 'Component diagrams' },
    ],
  },

  {
    id: 18,
    type: 'LLD',
    title: 'Design Library System',
    subtitle: 'Book inventory & lending',
    difficulty: 'Easy',
    companies: ['Amazon', 'Microsoft'],
    tags: ['OOP', 'CRUD', 'Search', 'Notifications'],
    duration: '35 mins',
    free: false,
    description: 'Design a library management system for tracking books, members, borrowing, returns, and overdue notifications.',
    inputOutput: {
      input:  'Member M001 borrows "Clean Code" (ISBN: 978-0-13) | Due in 14 days',
      output: 'Book marked Borrowed → Loan record created → Due date set → Return: Book marked Available',
    },
    coreConcepts: ['OOP', 'CRUD', 'Search Indexing', 'Observer for Notifications'],
    classes: ['Book', 'Member', 'Loan', 'Catalog', 'NotificationService'],
    expectedFunctions: [
      'borrowBook(memberId, isbn)',
      'returnBook(loanId)',
      'searchBooks(query)',
      'checkOverdue()',
    ],
    howToSolve: [
      'Book states: AVAILABLE → BORROWED → RESERVED',
      'Borrow: check availability → create Loan record → update Book status',
      'Search: index books by title, author, genre using HashMap/Trie',
      'Scheduler runs daily to detect overdue books and trigger notifications',
      'Lock book record during borrow to avoid concurrent borrowing issues',
    ],
    constraints: ['Concurrent borrowing prevention', 'Data consistency', 'Extensible features'],
    keyComponents: ['Book', 'Member', 'Loan', 'Catalog', 'NotificationService'],
    requirements: {
      functional:    ['Add/remove books', 'Search books', 'Borrow/return', 'Notify overdue', 'Inventory'],
      nonFunctional: ['Concurrent borrowing prevention', 'Data consistency', 'Extensible'],
    },
    resources: [
      { label: 'Library System — LeetCode Discuss', url: 'https://leetcode.com/discuss/interview-question/object-oriented-design/' },
      { label: 'Design Library Management System', url: 'https://www.geeksforgeeks.org/design-library-management-system/' },
    ],
    solveOptions: [
      { label: 'Code on Replit', url: 'https://replit.com/',          icon: '🔧', desc: 'Implement classes and logic' },
      { label: 'Draw UML',       url: 'https://app.diagrams.net/',    icon: '🗂️', desc: 'Class diagram' },
    ],
  },

  {
    id: 19,
    type: 'HLD',
    title: 'Design Payment Gateway',
    subtitle: 'Like Razorpay or Stripe',
    difficulty: 'Hard',
    companies: ['Amazon', 'Google'],
    tags: ['Transaction', 'ACID', 'Security', 'Idempotency'],
    duration: '60 mins',
    free: false,
    description: 'Design a payment processing system that handles transactions securely with idempotency and reliability.',
    inputOutput: {
      input:  'User pays ₹999 for order | Payment method: UPI | Merchant: Flipkart',
      output: 'Transaction initiated → Bank auth → Ledger updated → Webhook sent to merchant → Success',
    },
    coreConcepts: ['Idempotency Keys', 'ACID Transactions', 'Ledger', 'Fraud Detection'],
    classes: ['TransactionService', 'PaymentProcessor', 'FraudDetection', 'LedgerService', 'NotificationService'],
    expectedFunctions: [
      'initiatePayment(amount, method, merchantId)',
      'processPayment(transactionId)',
      'refund(transactionId)',
      'checkFraud(transaction)',
    ],
    howToSolve: [
      'Transaction flow: Client → Gateway → Payment Processor → Bank → Callback to merchant',
      'Idempotency: unique idempotency key per request prevents duplicate charges on retry',
      'Ledger Service: double-entry bookkeeping for accurate balance tracking',
      'Fraud Detection: real-time ML scoring on each transaction',
      'Webhook service notifies merchants of payment success/failure asynchronously',
    ],
    constraints: ['High availability', 'Idempotent requests', 'PCI DSS compliance', 'ACID transactions'],
    keyComponents: ['Transaction Service', 'Payment Processor', 'Fraud Detection', 'Ledger Service', 'Notification Service'],
    requirements: {
      functional:    ['Process payments', 'Refunds', 'Transaction history', 'Multi-currency', 'Webhooks'],
      nonFunctional: ['High availability', 'Idempotent', 'PCI DSS compliant', 'ACID'],
    },
    resources: [
      { label: 'Stripe Architecture Docs', url: 'https://stripe.com/docs/architecture' },
      { label: 'Razorpay Engineering Blog', url: 'https://engineering.razorpay.com/' },
    ],
    solveOptions: [
      { label: 'Draw on Excalidraw', url: 'https://excalidraw.com/',   icon: '✏️', desc: 'Architecture diagram' },
      { label: 'Use draw.io',        url: 'https://app.diagrams.net/', icon: '🗂️', desc: 'Sequence diagram' },
    ],
  },

  {
    id: 20,
    type: 'LLD',
    title: 'Design Vending Machine',
    subtitle: 'Automated product dispensing',
    difficulty: 'Easy',
    companies: ['Amazon', 'Apple'],
    tags: ['State Machine', 'OOP', 'Inventory', 'Strategy'],
    duration: '30 mins',
    free: false,
    description: 'Design a vending machine that dispenses products, handles payments, and manages inventory.',
    inputOutput: {
      input:  'Insert ₹20 → Select item B3 (₹15) → Confirm',
      output: 'Item B3 dispensed | Change returned: ₹5 | Inventory B3: 9 remaining',
    },
    coreConcepts: ['State Machine', 'Strategy Pattern', 'Inventory Management'],
    classes: ['VendingMachine', 'Product', 'PaymentModule', 'Inventory', 'Display'],
    expectedFunctions: [
      'insertMoney(amount)',
      'selectProduct(code)',
      'dispenseProduct()',
      'returnChange()',
      'restockProduct(code, quantity)',
    ],
    howToSolve: [
      'States: IDLE → MONEY_INSERTED → PRODUCT_SELECTED → DISPENSING → IDLE',
      'Strategy Pattern: cash, card, UPI payment handlers',
      'Check inventory before allowing product selection',
      'Calculate exact change after dispensing',
      'Observer Pattern: Display updates after each state transition',
    ],
    constraints: ['Multiple transaction handling', 'Extensible products', 'Inventory consistency'],
    keyComponents: ['VendingMachine', 'Product', 'PaymentModule', 'Inventory', 'Display'],
    requirements: {
      functional:    ['Insert money', 'Select product', 'Dispense', 'Return change', 'Restock'],
      nonFunctional: ['Multiple transactions', 'Extensible products', 'Inventory consistency'],
    },
    resources: [
      { label: 'Design Vending Machine — LeetCode Discuss', url: 'https://leetcode.com/discuss/interview-question/object-oriented-design/309769/Vending-Machine' },
    ],
    solveOptions: [
      { label: 'Code on Replit', url: 'https://replit.com/',          icon: '🔧', desc: 'Implement in Java/Python' },
      { label: 'Draw UML',       url: 'https://app.diagrams.net/',    icon: '🗂️', desc: 'State + class diagram' },
    ],
  },

  {
    id: 21,
    type: 'HLD',
    title: 'Design Airbnb',
    subtitle: 'Home rental marketplace',
    difficulty: 'Hard',
    companies: ['Amazon', 'Google'],
    tags: ['Search', 'Booking', 'Payments', 'Geo-search'],
    duration: '60 mins',
    free: false,
    description: 'Design a platform where users can list homes and book stays with real-time availability and payments.',
    inputOutput: {
      input:  'Search: "Beach house in Goa, Dec 24-28, 2 guests, budget ₹5000/night"',
      output: '12 available listings shown, sorted by relevance | Dates locked on selection → Payment → Confirmed',
    },
    coreConcepts: ['Geo-search', 'Date-based Availability', 'Distributed Locking', 'Reviews'],
    classes: ['ListingService', 'SearchService', 'BookingService', 'PaymentService', 'ReviewService'],
    expectedFunctions: [
      'searchListings(location, dateRange, filters)',
      'bookListing(listingId, userId, dateRange)',
      'processPayment(bookingId)',
      'addReview(listingId, userId, rating, comment)',
    ],
    howToSolve: [
      'Search: Elasticsearch with geospatial queries + date range filter',
      'Availability: calendar stored in DB, locked on booking initiation',
      'Booking flow: check availability → lock dates → payment → confirm',
      'Reviews stored per listing, aggregated rating computed and cached',
      'SQL for bookings/payments, NoSQL for listing content and reviews',
    ],
    constraints: ['Millions of users', 'Low latency search', 'Highly available booking'],
    keyComponents: ['Listing Service', 'Search Service', 'Booking Service', 'Payment Service', 'Review Service'],
    requirements: {
      functional:    ['List property', 'Search', 'Book stay', 'Process payment', 'Reviews'],
      nonFunctional: ['Millions of users', 'Low latency search', 'Highly available booking'],
    },
    resources: [
      { label: 'System Design: Airbnb (YT)', url: 'https://www.youtube.com/watch?v=F5wFw06qZHE' },
    ],
    solveOptions: [
      { label: 'Draw on Excalidraw', url: 'https://excalidraw.com/',   icon: '✏️', desc: 'Architecture diagram' },
      { label: 'Use draw.io',        url: 'https://app.diagrams.net/', icon: '🗂️', desc: 'Component diagram' },
    ],
  },

  {
    id: 22,
    type: 'LLD',
    title: 'Design Rate Limiter',
    subtitle: 'API throttling system',
    difficulty: 'Medium',
    companies: ['Amazon', 'Google', 'Netflix'],
    tags: ['Token Bucket', 'Sliding Window', 'Redis', 'API Gateway'],
    duration: '40 mins',
    free: false,
    description: 'Design a rate limiting system to throttle API requests per user or service using different algorithms.',
    inputOutput: {
      input:  'User U1 sends 150 requests/min (limit: 100/min)',
      output: 'First 100 requests: 200 OK | Requests 101-150: 429 Too Many Requests | Reset after 60s',
    },
    coreConcepts: ['Token Bucket', 'Sliding Window Counter', 'Redis Atomic Operations', 'Distributed Rate Limiting'],
    classes: ['RateLimiter', 'TokenBucket', 'SlidingWindowCounter', 'RedisCache', 'APIGateway'],
    expectedFunctions: [
      'isAllowed(userId, endpoint)',
      'refillTokens(userId)',
      'getRequestCount(userId, window)',
      'resetLimit(userId)',
    ],
    howToSolve: [
      'Token Bucket: each user has N tokens, refilled at fixed rate; request costs 1 token',
      'Sliding Window: track request timestamps in Redis sorted set, count in last 60s',
      'Redis INCR + EXPIRE for atomic counter-based rate limiting',
      'API Gateway intercepts all requests and calls rate limiter before forwarding',
      'Support different limits per endpoint (e.g., /login: 5/min, /search: 100/min)',
    ],
    constraints: ['Low latency check', 'Distributed deployment', 'Consistent enforcement'],
    keyComponents: ['RateLimiter', 'TokenBucket', 'SlidingWindow', 'RedisCache', 'API Gateway'],
    requirements: {
      functional:    ['Limit requests per second/minute', 'Return 429 on exceed', 'Reset periodically'],
      nonFunctional: ['Low latency', 'Distributed deployment', 'Consistent enforcement'],
    },
    resources: [
      { label: 'Design Rate Limiter — LeetCode #2502', url: 'https://leetcode.com/problems/design-a-rate-limiter/' },
      { label: 'Redis Rate Limiter Docs',              url: 'https://redis.io/docs/manual/patterns/rate-limiting/' },
    ],
    solveOptions: [
      { label: 'LeetCode #2502',   url: 'https://leetcode.com/problems/design-a-rate-limiter/', icon: '💻', desc: 'Direct LeetCode problem' },
      { label: 'Code on Replit',   url: 'https://replit.com/',                                   icon: '🔧', desc: 'Implement rate limiter' },
      { label: 'Draw UML',         url: 'https://app.diagrams.net/',                             icon: '🗂️', desc: 'Class/flow diagram' },
    ],
  },

  {
    id: 23,
    type: 'HLD',
    title: 'Design Notification System',
    subtitle: 'Push, SMS, Email at scale',
    difficulty: 'Medium',
    companies: ['Amazon', 'Meta', 'Google'],
    tags: ['Push Notifications', 'Kafka', 'Templates', 'Fan-out'],
    duration: '45 mins',
    free: false,
    description: 'Design a system that reliably sends notifications via push, email, and SMS to millions of users.',
    inputOutput: {
      input:  'Order #4521 placed → trigger "Order Confirmation" notification to user',
      output: 'Push sent to iOS/Android | Email sent via SES | SMS sent via Twilio | All within 2s',
    },
    coreConcepts: ['Kafka Event Queue', 'Fan-out', 'Template Engine', 'Retry with Dead Letter Queue'],
    classes: ['NotificationService', 'MessageQueue', 'TemplateEngine', 'DeliveryService', 'Scheduler'],
    expectedFunctions: [
      'sendNotification(userId, type, data)',
      'renderTemplate(templateId, data)',
      'deliverPush(deviceToken, payload)',
      'scheduleNotification(userId, time, message)',
    ],
    howToSolve: [
      'Producer publishes event to Kafka topic (e.g., order.placed)',
      'Notification Service consumes event, determines channels (push/email/SMS)',
      'Template Engine renders personalized content per user',
      'Channel-specific handlers: FCM/APNS for push, SES for email, Twilio for SMS',
      'Failed deliveries go to Dead Letter Queue for retry or manual inspection',
    ],
    constraints: ['Scale to millions', 'High availability', 'Low latency delivery', 'Retry logic'],
    keyComponents: ['Notification Service', 'Message Queue', 'Template Engine', 'Delivery Service', 'Scheduler'],
    requirements: {
      functional:    ['Send notifications', 'Multiple channels', 'Retry failed', 'Schedule notifications'],
      nonFunctional: ['Scale to millions', 'High availability', 'Low latency'],
    },
    resources: [
      { label: 'How Facebook delivers billions of notifications', url: 'https://highscalability.com/blog/2018/2/19/how-facebook-delivers-billions-of-notifications.html' },
    ],
    solveOptions: [
      { label: 'Draw on Excalidraw', url: 'https://excalidraw.com/',   icon: '✏️', desc: 'Architecture diagram' },
      { label: 'Use draw.io',        url: 'https://app.diagrams.net/', icon: '🗂️', desc: 'Component diagram' },
    ],
  },

  {
    id: 24,
    type: 'LLD',
    title: 'Design Logger Framework',
    subtitle: 'Logging library design',
    difficulty: 'Medium',
    companies: ['Amazon', 'Google', 'Microsoft'],
    tags: ['Observer', 'Singleton', 'Strategy', 'Thread-safe'],
    duration: '35 mins',
    free: false,
    description: 'Design a logging framework with multiple log levels, appenders (console/file/remote), and thread-safe operations.',
    inputOutput: {
      input:  'logger.error("DB connection failed", exception)',
      output: '[2024-01-15 09:32:11] [ERROR] [DBService] DB connection failed: java.sql.Exception... → written to file + sent to Splunk',
    },
    coreConcepts: ['Singleton Pattern', 'Observer Pattern', 'Strategy Pattern', 'Thread Safety'],
    classes: ['Logger', 'Appender', 'ConsoleAppender', 'FileAppender', 'RemoteAppender', 'Formatter', 'LogLevel'],
    expectedFunctions: [
      'log(level, message)',
      'addAppender(appender)',
      'setLogLevel(level)',
      'formatMessage(logRecord)',
    ],
    howToSolve: [
      'Logger as Singleton per module — one instance, thread-safe with synchronized',
      'Appender types: ConsoleAppender, FileAppender, RemoteAppender (Splunk/ELK)',
      'Observer Pattern: each Appender is a listener subscribed to Logger events',
      'Strategy Pattern: pluggable Formatter for JSON, plain text, XML output',
      'Log levels hierarchy: TRACE < DEBUG < INFO < WARN < ERROR < FATAL',
    ],
    constraints: ['Thread-safe', 'Extensible appenders', 'Minimal performance overhead'],
    keyComponents: ['Logger', 'Appender', 'Formatter', 'LogLevel', 'Configuration'],
    requirements: {
      functional:    ['Log messages', 'Multiple levels', 'Custom formats', 'Multiple appenders'],
      nonFunctional: ['Thread-safe', 'Extensible', 'Minimal overhead'],
    },
    resources: [
      { label: 'Design Logger — LeetCode #359', url: 'https://leetcode.com/problems/logger-rate-limiter/' },
      { label: 'Martin Fowler: Enterprise Logging', url: 'https://martinfowler.com/articles/enterpriseLogging.html' },
    ],
    solveOptions: [
      { label: 'LeetCode #359',   url: 'https://leetcode.com/problems/logger-rate-limiter/', icon: '💻', desc: 'Related LeetCode problem' },
      { label: 'Code on Replit',  url: 'https://replit.com/',                                 icon: '🔧', desc: 'Implement logging classes' },
      { label: 'Draw UML',        url: 'https://app.diagrams.net/',                           icon: '🗂️', desc: 'Class diagram' },
    ],
  },

  {
    id: 25,
    type: 'HLD',
    title: 'Design Distributed Cache',
    subtitle: 'Like Redis/Memcached',
    difficulty: 'Hard',
    companies: ['Amazon', 'Google', 'Netflix'],
    tags: ['Consistent Hashing', 'Eviction', 'Replication', 'Fault Tolerance'],
    duration: '60 mins',
    free: false,
    description: 'Design a distributed caching system with consistent hashing, replication, eviction policies, and fault tolerance.',
    inputOutput: {
      input:  'set("user:1234", userData, TTL=3600) | get("user:1234")',
      output: 'Key hashed → routed to Node 3 → replicated to Node 4 | get returns value in < 1ms',
    },
    coreConcepts: ['Consistent Hashing', 'LRU/LFU Eviction', 'Replication', 'Virtual Nodes'],
    classes: ['CacheNode', 'ConsistentHashRing', 'ReplicationManager', 'EvictionPolicy', 'ClientLibrary'],
    expectedFunctions: [
      'get(key)',
      'set(key, value, ttl)',
      'delete(key)',
      'rebalanceOnNodeFailure(failedNode)',
    ],
    howToSolve: [
      'Consistent hashing with virtual nodes to map keys to cache nodes',
      'Replication: each key replicated to N successor nodes on the ring',
      'Eviction: LRU (Least Recently Used) or LFU (Least Frequently Used) per node',
      'Client library handles node lookup, retry, and failover transparently',
      'Failure: heartbeat detects dead node → keys reassigned to next node on ring',
    ],
    constraints: ['High throughput', 'Low latency < 1ms', 'Fault-tolerant', 'Horizontal scaling'],
    keyComponents: ['Cache Node', 'Consistent Hashing', 'Replication', 'Eviction Policy', 'Client Library'],
    requirements: {
      functional:    ['Read/write cache', 'Replication', 'Eviction', 'Client API'],
      nonFunctional: ['High throughput', 'Low latency', 'Fault-tolerant', 'Scalable'],
    },
    resources: [
      { label: 'Redis Cluster Tutorial',              url: 'https://redis.io/docs/management/scaling/' },
      { label: 'LRU Cache — LeetCode #146',          url: 'https://leetcode.com/problems/lru-cache/' },
      { label: 'LFU Cache — LeetCode #460',          url: 'https://leetcode.com/problems/lfu-cache/' },
    ],
    solveOptions: [
      { label: 'LeetCode #146 (LRU)', url: 'https://leetcode.com/problems/lru-cache/', icon: '💻', desc: 'Implement LRU Cache' },
      { label: 'LeetCode #460 (LFU)', url: 'https://leetcode.com/problems/lfu-cache/', icon: '💻', desc: 'Implement LFU Cache' },
      { label: 'Draw on Excalidraw',  url: 'https://excalidraw.com/',                  icon: '✏️', desc: 'Architecture diagram' },
    ],
  },

  {
    id: 26,
    type: 'LLD',
    title: 'Design Food Delivery App',
    subtitle: 'Like Swiggy or Zomato',
    difficulty: 'Medium',
    companies: ['Amazon', 'Uber'],
    tags: ['OOP', 'Order Management', 'Tracking', 'State Machine'],
    duration: '45 mins',
    free: false,
    description: 'Design a food delivery system with restaurants, orders, delivery partners, and real-time tracking.',
    inputOutput: {
      input:  'User orders "Biryani" from Hotel Saravana Bhavan | Payment: UPI',
      output: 'Order confirmed → Restaurant accepts → Delivery partner assigned → ETA: 30 min → Delivered',
    },
    coreConcepts: ['State Machine', 'Observer Pattern', 'Strategy Pattern (Pricing)', 'OOP'],
    classes: ['Order', 'Restaurant', 'Menu', 'DeliveryPartner', 'TrackingService', 'PaymentService'],
    expectedFunctions: [
      'placeOrder(userId, restaurantId, items)',
      'assignDeliveryPartner(orderId)',
      'updateOrderStatus(orderId, status)',
      'trackOrder(orderId)',
    ],
    howToSolve: [
      'Order states: PLACED → ACCEPTED → PREPARING → PICKED_UP → DELIVERED',
      'Observer Pattern: notify customer at each state transition',
      'Delivery partner matched by proximity (nearest available partner)',
      'GPS tracking: partner location polled every 10s and sent to customer',
      'Strategy Pattern: pricing (normal, surge, free delivery above ₹299)',
    ],
    constraints: ['Multiple simultaneous orders', 'Real-time tracking', 'Low latency updates'],
    keyComponents: ['Restaurant', 'Menu', 'Order', 'DeliveryPartner', 'TrackingService'],
    requirements: {
      functional:    ['Place order', 'Assign partner', 'Track order', 'Cancel', 'Payment'],
      nonFunctional: ['Multiple simultaneous orders', 'Real-time tracking', 'Low latency'],
    },
    resources: [
      { label: 'System Design: Food Delivery (YT)', url: 'https://www.youtube.com/watch?v=uz9TJXc8oiM' },
    ],
    solveOptions: [
      { label: 'Code on Replit',     url: 'https://replit.com/',          icon: '🔧', desc: 'Implement classes and logic' },
      { label: 'Draw UML',           url: 'https://app.diagrams.net/',    icon: '🗂️', desc: 'Class diagram' },
    ],
  },

  {
    id: 27,
    type: 'HLD',
    title: 'Design Stock Exchange',
    subtitle: 'High-frequency trading platform',
    difficulty: 'Hard',
    companies: ['Amazon', 'Google', 'Apple'],
    tags: ['Order Book', 'Matching Engine', 'Low Latency', 'Priority Queue'],
    duration: '75 mins',
    free: false,
    description: 'Design a platform for high-frequency trading with order matching, market data streaming, and risk management.',
    inputOutput: {
      input:  'Buy order: 100 shares of TCS @ ₹3500 | Sell order: 100 shares of TCS @ ₹3498',
      output: 'Orders matched at ₹3499 (mid) | Trade executed | Market data feed updated | Both parties notified',
    },
    coreConcepts: ['Order Book (Priority Queue)', 'Price-Time Priority Matching', 'Market Data Feed', 'CQRS'],
    classes: ['OrderBook', 'MatchingEngine', 'MarketDataFeed', 'TradeExecutor', 'RiskManager'],
    expectedFunctions: [
      'placeOrder(order)',
      'cancelOrder(orderId)',
      'matchOrders()',
      'publishMarketData(trade)',
    ],
    howToSolve: [
      'Order book: MaxHeap for buy orders (highest price first), MinHeap for sell orders',
      'Matching: if best buy price >= best sell price → execute trade',
      'Price-time priority: same price → earlier order gets filled first',
      'Market data feed: publish trade events to subscribers via pub/sub',
      'Risk checks: reject orders exceeding position limits before matching',
    ],
    constraints: ['Low latency < 1ms', 'High throughput', 'Fault-tolerant', 'Scalable'],
    keyComponents: ['Order Book', 'Matching Engine', 'Market Data Feed', 'Trade Execution', 'Risk Management'],
    requirements: {
      functional:    ['Place/cancel orders', 'Match orders', 'Stream market data', 'Multiple instruments'],
      nonFunctional: ['Low latency < 1ms', 'High throughput', 'Fault-tolerant', 'Scalable'],
    },
    resources: [
      { label: 'System Design: Stock Exchange (YT)', url: 'https://www.youtube.com/watch?v=BRuM1l0M0Zc' },
      { label: 'Design Stock Exchange — LeetCode Discuss', url: 'https://leetcode.com/discuss/interview-question/object-oriented-design/' },
    ],
    solveOptions: [
      { label: 'Draw on Excalidraw', url: 'https://excalidraw.com/',   icon: '✏️', desc: 'Architecture diagram' },
      { label: 'Use draw.io',        url: 'https://app.diagrams.net/', icon: '🗂️', desc: 'Component diagram' },
    ],
  },

  {
    id: 28,
    type: 'LLD',
    title: 'Design Car Rental System',
    subtitle: 'Vehicle booking & management',
    difficulty: 'Medium',
    companies: ['Amazon', 'Uber'],
    tags: ['OOP', 'Booking', 'Availability', 'Concurrent Locking'],
    duration: '40 mins',
    free: false,
    description: 'Design a car rental system with vehicle inventory, booking, availability tracking, and payment.',
    inputOutput: {
      input:  'User books Honda City (ID: CAR-042) from Jan 5–8 (3 days) | ₹1200/day',
      output: 'Car locked → Payment confirmed → Booking created | Booking ID: BK-9821 | Total: ₹3600',
    },
    coreConcepts: ['Optimistic Locking', 'Observer Pattern', 'Strategy (Pricing)', 'OOP'],
    classes: ['Car', 'Customer', 'Booking', 'Payment', 'InventoryService', 'PricingStrategy'],
    expectedFunctions: [
      'searchAvailableCars(dateRange, type)',
      'bookCar(customerId, carId, dateRange)',
      'cancelBooking(bookingId)',
      'calculateRentalFee(carId, days)',
    ],
    howToSolve: [
      'Car states: AVAILABLE → RESERVED → RENTED → MAINTENANCE',
      'Booking flow: check availability → lock car → confirm payment → create booking',
      'Optimistic locking with version number to handle concurrent booking attempts',
      'Observer Pattern: notify customer of booking confirmation, reminders, return alerts',
      'Strategy Pattern: pricing varies by car type (economy, luxury) and duration (daily, weekly)',
    ],
    constraints: ['No double bookings', 'Concurrent booking prevention', 'Multiple car types'],
    keyComponents: ['Car', 'Customer', 'Booking', 'Payment', 'InventoryService'],
    requirements: {
      functional:    ['Search cars', 'Book car', 'Cancel booking', 'Track availability'],
      nonFunctional: ['No double booking', 'Low latency search', 'Extensible vehicle types'],
    },
    resources: [
      { label: 'Car Rental LLD — LeetCode Discuss', url: 'https://leetcode.com/discuss/interview-question/object-oriented-design/124565/' },
    ],
    solveOptions: [
      { label: 'Code on Replit', url: 'https://replit.com/',          icon: '🔧', desc: 'Implement classes and logic' },
      { label: 'Draw UML',       url: 'https://app.diagrams.net/',    icon: '🗂️', desc: 'Class diagram' },
    ],
  },

  {
    id: 29,
    type: 'HLD',
    title: 'Design Google Maps',
    subtitle: 'Navigation & routing at scale',
    difficulty: 'Hard',
    companies: ['Google', 'Uber', 'Apple'],
    tags: ['Graph', 'Dijkstra', 'A*', 'ETA', 'Traffic'],
    duration: '75 mins',
    free: false,
    description: 'Design a navigation platform with real-time routing, traffic-aware path finding, and ETA prediction.',
    inputOutput: {
      input:  'Route from Chennai Central to Chennai Airport | Current time: 8:30 AM (peak traffic)',
      output: 'Fastest route: NH48 via Pallavaram | ETA: 42 min (traffic-adjusted) | 3 alternatives shown',
    },
    coreConcepts: ['Dijkstra/A* Algorithm', 'Graph with Dynamic Weights', 'Geohashing', 'Map Tiles'],
    classes: ['MapService', 'RoutingEngine', 'TrafficService', 'SearchService', 'ETACalculator'],
    expectedFunctions: [
      'findRoute(origin, destination, mode)',
      'updateTrafficWeights(segment, congestion)',
      'searchLocation(query)',
      'calculateETA(route, currentTraffic)',
    ],
    howToSolve: [
      'Road network as weighted graph: intersections as nodes, roads as edges',
      'Dijkstra for shortest path, A* for faster heuristic-based routing',
      'Traffic service updates edge weights dynamically based on live sensor data',
      'ETA = historical avg travel time + live traffic adjustment per segment',
      'Geocoding: location name → coordinates (lat/lng) via search index',
    ],
    constraints: ['Global scale', 'Low latency routing < 200ms', 'Highly available', 'Real-time traffic'],
    keyComponents: ['Map Service', 'Routing Engine', 'Traffic Service', 'Search Service', 'ETA Calculator'],
    requirements: {
      functional:    ['Route calculation', 'Search locations', 'Traffic updates', 'ETA', 'Turn-by-turn'],
      nonFunctional: ['Global scale', 'Low latency routing', 'Highly available'],
    },
    resources: [
      { label: 'Google Maps Architecture — High Scalability', url: 'https://highscalability.com/blog/2014/2/26/google-maps-architecture.html' },
      { label: 'Network Delay Time — LeetCode #743',          url: 'https://leetcode.com/problems/network-delay-time/' },
    ],
    solveOptions: [
      { label: 'LeetCode #743 (Dijkstra)', url: 'https://leetcode.com/problems/network-delay-time/', icon: '💻', desc: 'Practice Dijkstra algorithm' },
      { label: 'Draw on Excalidraw',       url: 'https://excalidraw.com/',                           icon: '✏️', desc: 'System diagram' },
      { label: 'Use draw.io',              url: 'https://app.diagrams.net/',                         icon: '🗂️', desc: 'Component diagram' },
    ],
  },

  {
    id: 30,
    type: 'LLD',
    title: 'Design Call Taxi Booking System',
    subtitle: 'Like Uber / Ola',
    difficulty: 'Medium',
    companies: ['Zoho', 'Uber', 'Amazon'],
    tags: ['OOP', 'Strategy Pattern', 'Observer Pattern', 'Scheduling'],
    duration: '45 mins',
    free: false,
    description: 'Design a taxi booking system where users book taxis, drivers get auto-assigned, and fares are calculated by distance.',
    inputOutput: {
      input:  'Passenger at (12.97, 80.24) requests cab | 3 drivers nearby',
      output: 'Nearest driver D2 (0.8km) assigned | ETA: 3 min | Fare estimate: ₹85',
    },
    coreConcepts: ['Observer Pattern', 'Strategy Pattern (Fare)', 'Distance-based Matching', 'OOP'],
    classes: ['TaxiBookingService', 'Driver', 'Passenger', 'Ride', 'LocationService', 'FareCalculator'],
    expectedFunctions: [
      'requestRide(passengerId, location)',
      'findNearestDriver(location)',
      'startRide(rideId)',
      'endRide(rideId)',
      'calculateFare(distance, rideType)',
    ],
    howToSolve: [
      'Find nearest available driver: calculate Haversine distance to all nearby drivers',
      'Ride states: REQUESTED → ACCEPTED → STARTED → COMPLETED / CANCELLED',
      'Observer Pattern: notify both driver and passenger on status change',
      'Strategy Pattern: Normal fare vs Surge fare (1.5x during peak hours)',
      'LocationService tracks driver GPS positions, updated every 10 seconds',
    ],
    constraints: ['Multiple simultaneous bookings', 'Driver location updates', 'Low latency matching'],
    keyComponents: ['TaxiBookingService', 'Driver', 'Passenger', 'Ride', 'LocationService', 'FareCalculator'],
    requirements: {
      functional:    ['Book taxi', 'Assign nearest driver', 'Start/end ride', 'Calculate fare', 'Ride history'],
      nonFunctional: ['Multiple simultaneous bookings', 'Driver location updates', 'Low latency matching'],
    },
    resources: [
      { label: 'Taxi Booking LLD — LeetCode Discuss', url: 'https://leetcode.com/discuss/interview-question/object-oriented-design/' },
      { label: 'Uber Engineering Blog',                url: 'https://eng.uber.com/' },
    ],
    solveOptions: [
      { label: 'Draw UML',       url: 'https://app.diagrams.net/', icon: '🗂️', desc: 'Class diagram' },
      { label: 'Code on Replit', url: 'https://replit.com/',       icon: '🔧', desc: 'Implement in Java' },
    ],
  },
]